=== BackupTheBerlios/reportasistent-svn/trunk/Setup/Setup_accessories/4ftAR2NL/dtd/ar2nl-1.2.dtd
<!-- AR2NL DTD 1.2 -->

<!-- This is DTD for data of the AR2NL system. 
     Please use the following formal public identifier to identify it:
     
     "-//LISp-Miner//DTD AR2NL 1.2//EN"
     
     If your document's top-level element is Formulation pattern,
     use this DOCTYPE declaration:
     
     <!DOCTYPE formulationpatterns PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
     	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">
	
     If your document's top-level element is Auxiliary symbol,
     use this DOCTYPE declaration:
     
     <!DOCTYPE auxiliarysymbols PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">
	
     If your document's top-level element is pattern for nouns,
     use this DOCTYPE declaration:
     
     <!DOCTYPE mnpatterns PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">
     
     If your document's top-level element is pattern for verbs,
     use this DOCTYPE declaration:
     
     <!DOCTYPE mvpatterns PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">
     
     If your document's top-level element is Entity,
     use this DOCTYPE declaration:
     
     <!DOCTYPE entitynames PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">
     
     If your document's top-level element is Elementary expression,
     use this DOCTYPE declaration:
     
     <!DOCTYPE elementaryexpressions PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
     	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">
	
     If your document's top-level element is file with language parameters,
     use this DOCTYPE declaration:
     
     <!DOCTYPE langparameters PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
     	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">

-->


<!-- entities -->

<!ENTITY % directive
           "case   (1|2|3|4|5|6|7|_|nom|gen|par|ess|tra|ine|ela|ill|ade|abl|all|abe|kom|ins) #IMPLIED
	    number (sg|pl|qpl|_)     #IMPLIED">

<!ENTITY % entity.symbol "symbol (E|Edefart|Edemonstr|Eid1|Eid2|Eindefart|Epers|Eptc0|Eptc1|Erel|EPtcPatternSuffix) #REQUIRED">

<!ENTITY % fpa.symbol "symbol (A|C|X|Y|Z) #REQUIRED">

<!ENTITY % role.symbol "role (A|S|C) #REQUIRED">

<!ENTITY % numofant "numofant CDATA #REQUIRED">
<!ENTITY % numofsuc "numofsuc CDATA #REQUIRED">
<!ENTITY % numofcon "numofcon CDATA #REQUIRED">

<!-- common elements -->

<!ELEMENT literal EMPTY>
<!ATTLIST literal %role.symbol;
		  typeofphrase (L|N|R|V|NA) #REQUIRED
                  %directive;
		  vderivation  (ptc)     #IMPLIED>

<!ELEMENT word (#PCDATA)>
<!ATTLIST word pattern CDATA #REQUIRED
               class (nominal|verb) #REQUIRED>

<!ELEMENT optionaltext (#PCDATA|choosetext)*>

<!ELEMENT choosetext (variant+)>

<!ELEMENT variant (#PCDATA)>

<!ELEMENT param EMPTY>
<!ATTLIST param name (B|P|T|N) #REQUIRED>

<!ELEMENT ename EMPTY>
<!ATTLIST ename %entity.symbol;
                %directive;>

<!ELEMENT floatslot EMPTY>
<!ATTLIST floatslot id CDATA #REQUIRED
                    %role.symbol;
		    occno (first|last) #REQUIRED>

<!-- formulation patterns -->

<!ELEMENT formulationpatterns (fp*)>

<!ELEMENT fp (#PCDATA|choosetext|ename|floatslot|fpa|literal|optionaltext|param)*>
<!ATTLIST fp id         ID      #REQUIRED
             quantifier (AAI|FUI|DFUI)   #REQUIRED
	     %numofant;
	     %numofsuc;
	     %numofcon;>

<!ELEMENT fpa EMPTY>
<!ATTLIST fpa %fpa.symbol;
              %directive;>

<!-- entities -->

<!ELEMENT entitynames (enamedata*)>

<!ELEMENT enamedata (#PCDATA|word)*>
<!ATTLIST enamedata id ID #REQUIRED
                    %entity.symbol;>

<!-- fpa - Formulation Patterns - Auxiliary -->

<!ELEMENT auxiliarysymbols (fpadata*)>

<!ELEMENT fpadata (#PCDATA|choosetext|ename|floatslot|fpa|literal|optionaltext|param)*>
<!ATTLIST fpadata id ID #REQUIRED
                  %fpa.symbol;
		  %numofant;
		  %numofsuc;
	          %numofcon;>

<!-- elementary expressions -->

<!ELEMENT elementaryexpressions (expression*)>

<!ELEMENT expression (mbattribute, meaning, (APinv|NPinv|VPinv)*, categories)>
<!ATTLIST expression id ID #REQUIRED>

<!ELEMENT mbattribute (#PCDATA)>

<!ELEMENT meaning (#PCDATA)>

<!ELEMENT VPinv (#PCDATA|float|param|word)*>
<!ELEMENT APinv (#PCDATA|float|param|word)*>
<!ELEMENT NPinv (#PCDATA|float|param|word)*>

<!ELEMENT categories (category+)>

<!ELEMENT category (value, meaning, adjphrase*, nounphrase*, NAF*, verbphrase*)>

<!ELEMENT value (#PCDATA)>

<!ELEMENT adjphrase (#PCDATA|APinv|float|param|word)*>
<!ATTLIST adjphrase relposition (R|L) #REQUIRED>

<!ELEMENT nounphrase (#PCDATA|float|NPinv|param|word)*>
<!ATTLIST nounphrase %directive;>

<!ELEMENT NAF (#PCDATA|nounphrase)*>

<!ELEMENT verbphrase (#PCDATA|float|param|ptcmod|ptcmodslot|VPinv|word)*>

<!ELEMENT float (#PCDATA)>
<!ATTLIST float id CDATA #REQUIRED>

<!ELEMENT ptcmod (#PCDATA|param|VPinv|word)*>
<!ATTLIST ptcmod id CDATA #REQUIRED>

<!ELEMENT ptcmodslot EMPTY>
<!ATTLIST ptcmodslot id CDATA #REQUIRED>

<!-- common elements for patterns in MN and MV -->

<!ELEMENT pattern (example, (endsegment*|(base, pl, qpl?, ptc, ptcpattern?)))>
<!ATTLIST pattern name   CDATA #REQUIRED>

<!ELEMENT endsegment (#PCDATA)>
<!ATTLIST endsegment case   (1|2|3|4|5|6|7|nom|gen|par|ess|tra|ine|ela|ill|ade|abl|all|abe|kom|ins) #IMPLIED
		     number (sg|pl) #REQUIRED>
<!ELEMENT base (#PCDATA)>
<!ELEMENT pl (#PCDATA)>
<!ELEMENT qpl (#PCDATA)>
<!ELEMENT ptc (#PCDATA)>
<!ATTLIST ptc recommended (yes|no) "yes">
<!ELEMENT ptcpattern (#PCDATA)>
<!ELEMENT example (#PCDATA)>

<!-- MN patterns -->

<!ELEMENT mnpatterns (pattern*)>

<!-- MV patterns -->

<!ELEMENT mvpatterns (pattern*)>

<!-- Language parameter -->

<!ELEMENT langparameters (langparam*)>

<!ELEMENT langparam EMPTY>
<!ATTLIST langparam name (conjunction|participle.position|decimal.point.symbol) #REQUIRED
	            value CDATA #REQUIRED>

=== BackupTheBerlios/reportasistent-svn/trunk/4ftAR2NL/_data/cs/fp.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE formulationpatterns PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">

<formulationpatterns>

<!-- formulation patterns for Founded Implication -->

<fp id="fp1" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="0">
  01. <fpa symbol="X"/> <ename symbol="Eptc0" case="2" number="pl"/>
  <ename symbol="E" case="2" number="pl"/>
  potvrzuje tuto závislost: jestliže <floatslot id="1" role="A" occno="first"/>
  <ename symbol="E"/>
  <literal role="A" typeofphrase="V"/>, pak
  <floatslot id="1" role="S" occno="first"/>
  <optionaltext>
    <choosetext>
      <variant>také</variant>
      <variant>rovněž</variant>
    </choosetext>
  </optionaltext>
  <literal role="S" typeofphrase="V"/>.
</fp>

<fp id="fp2" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="1+">
  02. <fpa symbol="X"/> <ename symbol="Eptc0" case="2" number="pl"/>
  <ename symbol="E" case="2" number="pl"/>
  potvrzuje tuto závislost: jestliže <floatslot id="1" role="A" occno="first"/>
  <ename symbol="E"/>
  <literal role="A" typeofphrase="V"/>, pak
  <floatslot id="1" role="S" occno="first"/>
  <optionaltext>
    <choosetext>
      <variant>také</variant>
      <variant>rovněž</variant>
    </choosetext>
  </optionaltext>
  <literal role="S" typeofphrase="V"/>.
  <fpa symbol="C"/>
</fp>


<fp id="fp3" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="0">
  03. <fpa symbol="Y"/>
  <floatslot id="1" role="S" occno="first"/>
  <optionaltext>
    <choosetext>
      <variant>také</variant>
      <variant>rovněž</variant>
    </choosetext>
  </optionaltext>
  <literal role="S" typeofphrase="V"/>.
  <fpa symbol="Z"/>
</fp>

<fp id="fp4" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="1+">
  04. <fpa symbol="Y"/>
  <floatslot id="1" role="S" occno="first"/>
  <optionaltext>
    <choosetext>
      <variant>také</variant>
      <variant>rovněž</variant>
    </choosetext>
  </optionaltext>
  <literal role="S" typeofphrase="V"/>.
  <fpa symbol="Z"/>
 <fpa symbol="C"/>
</fp>



<fp id="fp5" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="0">
  05. <fpa symbol="Y" case="1" number="pl"/>
  <floatslot id="1" role="S" occno="first"/>
  <optionaltext>
    <choosetext>
      <variant>také</variant>
      <variant>rovněž</variant>
    </choosetext>
  </optionaltext>
  <literal role="S" typeofphrase="V" number="pl"/>.
  <fpa symbol="Z"/>
</fp>

<fp id="fp6" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="1+">
  06. <fpa symbol="Y" case="1" number="pl"/>
  <floatslot id="1" role="S" occno="first"/>
  <optionaltext>
    <choosetext>
      <variant>také</variant>
      <variant>rovněž</variant>
    </choosetext>
  </optionaltext>
  <literal role="S" typeofphrase="V" number="pl"/>.
  <fpa symbol="Z"/>
  <fpa symbol="C"/>
</fp>

<fp id="fp7" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="0">
  07. <fpa symbol="X"/>
  <fpa symbol="Y" case="2" number="pl"/>
  <floatslot id="1" role="S" occno="first"/>
  <optionaltext>
    <choosetext>
      <variant>také</variant>
      <variant>rovněž</variant>
    </choosetext>
  </optionaltext>
  <literal role="S" typeofphrase="V" number="qpl"/>.
</fp>

<fp id="fp8" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="1+">
  08. <fpa symbol="X"/>
  <fpa symbol="Y" case="2" number="pl"/>
  <floatslot id="1" role="S" occno="first"/>
  <optionaltext>
    <choosetext>
      <variant>také</variant>
      <variant>rovněž</variant>
    </choosetext>
  </optionaltext>
  <literal role="S" typeofphrase="V" number="qpl"/>.
 <fpa symbol="C"/>
</fp>

<fp id="fp9" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="0">
  09. <fpa symbol="X"/>
  <fpa symbol="Y" case="2" number="pl"/> vykazuje
  <optionaltext>
    <choosetext>
      <variant>také</variant>
      <variant>rovněž</variant>
    </choosetext>
  </optionaltext>
  <literal role="S" typeofphrase="N" case="4"/>.
</fp>

<fp id="fp10" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="1+">
  10. <fpa symbol="X"/>
  <fpa symbol="Y" case="2" number="pl"/> vykazuje
  <optionaltext>
    <choosetext>
      <variant>také</variant>
      <variant>rovněž</variant>
    </choosetext>
  </optionaltext>
  <literal role="S" typeofphrase="N" case="4"/>.
 <fpa symbol="C"/>
</fp>


<fp id="fp11" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="0">
  11. Pro <fpa symbol="Y" case="4" number="pl"/> je charakteristické, že
  <floatslot id="1" role="S" occno="first"/>
  <optionaltext>
    <choosetext>
      <variant>také</variant>
      <variant>rovněž</variant>
    </choosetext>
  </optionaltext>
  <literal role="S" typeofphrase="V" number="pl"/>.
  (<fpa symbol="Z"/>)
</fp>

<fp id="fp12" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="1+">
  12. Pro <fpa symbol="Y" case="4" number="pl"/> je charakteristické, že
  <floatslot id="1" role="S" occno="first"/>
  <optionaltext>
    <choosetext>
      <variant>také</variant>
      <variant>rovněž</variant>
    </choosetext>
  </optionaltext>
  <literal role="S" typeofphrase="V" number="pl"/>.
  (<fpa symbol="Z"/>)
  <fpa symbol="C"/>
</fp>

<fp id="fp13" quantifier="FUI" numofant="2+" numofsuc="1+" numofcon="0">
  13. Kombinace <literal role="A" typeofphrase="N" case="2"/> a
  <literal role="A" typeofphrase="N" case="2"/> implikuje
  <literal role="S" typeofphrase="N" case="4"/>.
  <fpa symbol="Z"/>
</fp>

<fp id="fp14" quantifier="FUI" numofant="2+" numofsuc="1+" numofcon="1+">
  14. Kombinace <literal role="A" typeofphrase="N" case="2"/> a
  <literal role="A" typeofphrase="N" case="2"/> implikuje
  <literal role="S" typeofphrase="N" case="4"/>.
  <fpa symbol="Z"/>
  <fpa symbol="C"/>
</fp>

<!-- formulation patterns for Above Average -->

<fp id="fp101" quantifier="AAI" numofant="1+" numofsuc="1+" numofcon="0">
  01. Frekvence <literal role="S" typeofphrase="N" case="2"/>
  je o <param name="P"/> % vyšší mezi <fpa symbol="Y" case="7" number="pl"/>
  než v celé kolekci.
</fp>

<fp id="fp102" quantifier="AAI" numofant="1+" numofsuc="1+" numofcon="1+">
  02. Frekvence <literal role="S" typeofphrase="N" case="2"/>
  je o <param name="P"/> % vyšší mezi <fpa symbol="Y" case="7" number="pl"/>
  než v celé kolekci. Platí pro <param name="B"/> <ename symbol="E" case="2" number="pl"/>
  <ename symbol="Erel" number="pl"/> splňuji tyto podmínky:
    <ename symbol="E" case="1" number="sg"/>
	<literal role="C" typeofphrase="V"/>.
</fp>

<fp id="fp103" quantifier="AAI" numofant="1+" numofsuc="1+" numofcon="0">
  03. Frekvence
 <ename symbol="E" number="pl" case="2"/>,
 <ename symbol="Erel" number="pl"/>
 <literal role="S" typeofphrase="V" number="pl"/>
  je o <param name="P"/> % vyšší mezi <fpa symbol="Y" case="7" number="pl"/>
  než v celé kolekci.
</fp>

<fp id="fp104" quantifier="AAI" numofant="1+" numofsuc="1+" numofcon="1+">
  04. Frekvence
  <ename symbol="E" number="pl" case="2"/>,
  <ename symbol="Erel" number="pl"/>
  <literal role="S" typeofphrase="V" number="pl"/>
  je o <param name="P"/> % vyšší mezi <fpa symbol="Y" case="7" number="pl"/>
  než v celé kolekci. Platí pro <param name="B"/> <ename symbol="E" case="2" number="pl"/>
  <ename symbol="Erel" number="pl"/> splňuji tyto podmínky:
    <ename symbol="E" case="1" number="sg"/>
	<literal role="C" typeofphrase="V"/>.
</fp>


<!-- formulation patterns for Double Founded Implication -->

<fp id="fp201" quantifier="DFUI" numofant="1+" numofsuc="1+" numofcon="0">
  201. Z celkového počtu
	<param name="T"/>
	<ename symbol="E" case="2" number="pl"/>,
	<ename symbol="Erel" number="pl"/>
	<floatslot id="1" role="A" occno="first"/>
	<literal role="A" typeofphrase="V" number="pl"/>
	nebo
	<literal role="S" typeofphrase="V" number="pl"/>,
	<param name="P"/>% (konkrétně <param name="B"/>)
	<ename symbol="E" case="2" number="pl"/>
	
	<literal role="A" typeofphrase="V" number="pl"/>
	a zároveň
	<literal role="S" typeofphrase="V" number="pl"/>.
</fp>

<fp id="fp202" quantifier="DFUI" numofant="1+" numofsuc="1+" numofcon="1+">
  202.  Z celkového počtu
	<param name="T"/>
	<ename symbol="E" case="2" number="pl"/>,
	<ename symbol="Erel" number="pl"/>
	<floatslot id="1" role="A" occno="first"/>
	<literal role="A" typeofphrase="V" number="pl"/>
	nebo
	<literal role="S" typeofphrase="V" number="pl"/>,
	<param name="P"/>% (konkrétně <param name="B"/>)
	<ename symbol="E" case="2" number="pl"/>
	
	<literal role="A" typeofphrase="V" number="pl"/>
	a zároveň
	<literal role="S" typeofphrase="V" number="pl"/>.
	<fpa symbol="C"/>
</fp>

<fp id="fp203" quantifier="DFUI" numofant="1+" numofsuc="1+" numofcon="0">
  203. Z celkového počtu
	<param name="T"/>
	<fpa symbol="Y" case="2" number="pl"/>
	nebo
	<literal role="S" typeofphrase="V" number="pl"/>,
	<param name="P"/>% (konkrétně <param name="B"/>)
	<ename symbol="E" case="2" number="pl"/>
	
	<literal role="A" typeofphrase="V" number="pl"/>
	a zároveň
	<literal role="S" typeofphrase="V" number="pl"/>.
</fp>


<fp id="fp204" quantifier="DFUI" numofant="1+" numofsuc="1+" numofcon="1+">
  204.  Z celkového počtu
	<param name="T"/>
	<fpa symbol="Y" case="2" number="pl"/>
	nebo
	<literal role="S" typeofphrase="V" number="pl"/>,
	<param name="P"/>% (konkrétně <param name="B"/>)
	<ename symbol="E" case="2" number="pl"/>
	
	<literal role="A" typeofphrase="V" number="pl"/>
	a zároveň
	<literal role="S" typeofphrase="V" number="pl"/>.
	<fpa symbol="C"/>
</fp>

</formulationpatterns>

=== BackupTheBerlios/reportasistent-svn/trunk/Setup/Setup_accessories/4ftAR2NL/data/fi/fp.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE formulationpatterns PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">

<formulationpatterns>

<fp id="fp1" quantifier="FUI" numofant="1+" numofsuc="1+">
  <fpa symbol="X"/> havainnoidusta <ename symbol="E" case="ela" number="sg"/>
  toteuttaa seuraavan riippuvuuden: jos <ename symbol="E"/>
  <literal role="A" typeofphrase="V"/>, <ename symbol="Epers"/>
  <optionaltext></optionaltext>
  <literal role="S" typeofphrase="V"/>.
</fp>

<fp id="fp2" quantifier="FUI" numofant="1+" numofsuc="1+">
  <fpa symbol="Y" number="pl" />
  <optionaltext></optionaltext>
  <literal role="S" typeofphrase="V" number="pl"/>.
  <fpa symbol="Z"/>
</fp>

<fp id="fp3" quantifier="FUI" numofant="1+" numofsuc="1+">
  <fpa symbol="Y" number="pl"/> 
  <optionaltext></optionaltext>
  <literal role="S" typeofphrase="V" number="pl" />.
  <fpa symbol="Z"/>
</fp>

<fp id="fp4" quantifier="FUI" numofant="1+" numofsuc="1+">
  <fpa symbol="X"/> havainnoidusta 
  <ename symbol="E" case="ela" number="sg"/> toteuttaa seuraavan riippuvuuden:
  <fpa symbol="Y" number="pl"/>
  <optionaltext>myös</optionaltext>
  <literal role="S" typeofphrase="V" number="pl"/>.
</fp>

<fp id="fp5" quantifier="FUI" numofant="1+" numofsuc="1+">
  <fpa symbol="Y" case="all" number="pl"/>
  on ominaista, että he myös
  <literal role="S" typeofphrase="V"  number="pl"/>.
  (<fpa symbol="Z"/>)
</fp>

<fp id="fp6" quantifier="FUI" numofant="2+" numofsuc="1+">
  Yhdistelmästä <literal role="A" typeofphrase="N"/> ja
  <literal role="A" typeofphrase="N"/>  seuraa
  <literal role="S" typeofphrase="N"/>.
  <fpa symbol="Z"/>
</fp>

<!-- formulation patterns for Above Average -->

<fp id="fp10" quantifier="AAI" numofant="1+" numofsuc="1+">
  Potilaiden, joilla on ominaisuus <literal role="S" typeofphrase="N" case="gen"/>, 
  suhteellinen osuus
  on <param name="P"/> % korkeampi niiden <fpa symbol="Y" case="gen" number="pl"/>
  joukossa kuin koko tarkasteltavassa ryhmässä. 
  (Kaikki nämä ehdot toteuttaa  <param name="B"/> 
  <ename symbol="E" case="par" number="sg"/>.)
</fp>

</formulationpatterns>

=== BackupTheBerlios/reportasistent-svn/trunk/4ftAR2NL/_data/cs/mv.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mvpatterns PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">

<mvpatterns>
<pattern name="v1">
  <example>pije</example>
  <base>e</base>
  <pl>í</pl>
  <qpl>e</qpl>
  <ptc>ící</ptc>
  <ptcpattern>a2</ptcpattern>
</pattern>

<pattern name="v2">
  <example>kouří</example>
  <base></base>
  <pl></pl>
  <qpl></qpl>
  <ptc>cí</ptc>
  <ptcpattern>a2</ptcpattern>
</pattern>

<pattern name="v3">
  <example>má, dělá</example>
  <base>á</base>
  <pl>ají</pl>
  <qpl>á</qpl>
  <ptc>ající</ptc>
  <ptcpattern></ptcpattern>
</pattern>

<pattern name="vi01">
  <example>myslí, podílí</example>
  <base>í</base>
  <pl>í</pl>
  <qpl>elo</qpl>
  <ptc>ející</ptc>
  <ptcpattern>a2</ptcpattern>
</pattern>

<pattern name="vp1">
  <example>absolvoval</example>
  <base>l</base>
  <pl>li</pl>
  <qpl>lo</qpl>
  <ptc recommended="no">vší</ptc>
  <ptcpattern>a2</ptcpattern>
</pattern>

<pattern name="vp2">
  <example>neuvedl</example>
  <base>l</base>
  <pl>li</pl>
  <qpl>lo</qpl>
  <ptc recommended="no">ší</ptc>
  <ptcpattern>a2</ptcpattern>
</pattern>

<pattern name="vx1">
  <example>je (být)</example>
  <base>e</base>
  <pl>sou</pl>
  <qpl>e</qpl>
  <ptc></ptc>
  <ptcpattern></ptcpattern>
</pattern>

</mvpatterns>

=== BackupTheBerlios/reportasistent-svn/trunk/Setup/Setup_accessories/4ftAR2NL/data/en/mn.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mnpatterns PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">

<mnpatterns>

<pattern name="a1">
  <example>a</example>
  <endsegment number="sg">a</endsegment>
  <endsegment number="pl"></endsegment>
</pattern>
<pattern name="n1">
  <example>patient</example>
  <endsegment number="sg"></endsegment>
  <endsegment number="pl">s</endsegment>
</pattern>
<pattern name="n1y">
  <example>country</example>
  <endsegment number="sg">y</endsegment>
  <endsegment number="pl">ies</endsegment>
</pattern>
<pattern name="p0">
  <example>having</example>
  <endsegment number="sg"></endsegment>
  <endsegment number="pl"></endsegment>
</pattern>
<pattern name="ppm">
  <example>his - their</example>
  <endsegment number="sg">his</endsegment>
  <endsegment number="pl">their</endsegment>
</pattern>

</mnpatterns>

=== BackupTheBerlios/reportasistent-svn/trunk/Setup/Setup_accessories/4ftAR2NL/data/en/fp.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE formulationpatterns PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">

<formulationpatterns>

<fp id="fp1" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="0" show="yes">
  <choosetext>
    <variant>This fact</variant>
    <variant>This hypothesis</variant>
    <variant>This rule</variant>
  </choosetext>  
  <fpa symbol="X"/>
  observed
  <ename symbol="E" number="pl"/>
  show this relation: if the
  <ename symbol="E"/>
  <literal role="A" typeofphrase="V"/>
  , then
  <ename symbol="Epers"/>
  <optionaltext>also</optionaltext>
  <literal role="S" typeofphrase="V"/>
  .
</fp>

<fp id="fp2" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="1+" show="yes">
  <fpa symbol="X"/>
  observed
  <ename symbol="E" number="pl"/>
  show this relation: if the
  <ename symbol="E"/>
  <literal role="A" typeofphrase="V"/>
  , then
  <ename symbol="Epers"/>
  <optionaltext>also</optionaltext>
  <literal role="S" typeofphrase="V"/>
  .
  <fpa symbol="C"/>
</fp>

<fp id="fp3" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="0" show="yes">
   <ename symbol="Eindefart"/>
  <fpa symbol="Y"/>
  <optionaltext>also</optionaltext>
  <literal role="S" typeofphrase="V"/>
  .
  <fpa symbol="Z"/>
 
</fp>

<fp id="fp4" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="1+" show="yes">
  <ename symbol="Eindefart"/>
  <fpa symbol="Y"/>
  <optionaltext>also</optionaltext>
  <literal role="S" typeofphrase="V"/>
  .
  <fpa symbol="Z"/>
  <fpa symbol="C"/>
</fp>

<fp id="fp5" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="0" show="yes">
  <fpa symbol="Y" number="pl"/>
  <optionaltext>also</optionaltext>
  <literal role="S" typeofphrase="V" number="pl"/>
  .
  <fpa symbol="Z"/>
</fp>

<fp id="fp6" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="1+" show="yes">
  <fpa symbol="Y" number="pl"/>
  <optionaltext>also</optionaltext>
  <literal role="S" typeofphrase="V" number="pl"/>
  .
  <fpa symbol="Z"/>
  <fpa symbol="C"/>
</fp>

<fp id="fp7" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="0" show="yes">
  <fpa symbol="X"/>
  <fpa symbol="Y" number="pl"/>
  <optionaltext>also</optionaltext>
  <literal role="S" typeofphrase="V" number="pl"/>
  .
</fp>

<fp id="fp8" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="1+" show="yes">
  <fpa symbol="X"/>
  <fpa symbol="Y" number="pl"/>
  <optionaltext>also</optionaltext>
  <literal role="S" typeofphrase="V" number="pl"/>
  .
  <fpa symbol="C"/>
</fp>

<fp id="fp9" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="0" show="yes">
  It is characteristic for the
  <fpa symbol="Y" number="pl"/>
  that they also
  <literal role="S" typeofphrase="V" number="pl"/>
  .(
  <fpa symbol="Z"/>
  )
</fp>

<fp id="fp10" quantifier="FUI" numofant="1+" numofsuc="1+" numofcon="1+" show="yes">
  It is characteristic for the
  <fpa symbol="Y" number="pl"/>
  that they also
  <literal role="S" typeofphrase="V" number="pl"/>
  .(
  <fpa symbol="Z"/>
  )
  <fpa symbol="C"/>
</fp>

<fp id="fp11" quantifier="FUI" numofant="2+" numofsuc="1+" numofcon="0" show="yes">
  A combination of
  <literal role="A" typeofphrase="N"/>
  and
  <literal role="A" typeofphrase="N"/>
  implies
  <literal role="S" typeofphrase="N"/>
  .
  <fpa symbol="Z"/>
</fp>

<fp id="fp12" quantifier="FUI" numofant="2+" numofsuc="1+" numofcon="1+" show="yes">
  A combination of
  <literal role="A" typeofphrase="N"/>
  and
  <literal role="A" typeofphrase="N"/>
  implies
  <literal role="S" typeofphrase="N"/>
  .
  <fpa symbol="Z"/>
  <fpa symbol="C"/>
</fp>

<!-- above average -->

<fp id="fp101" quantifier="AAI" numofant="1+" numofsuc="1+" numofcon="0" show="yes">
  The relative frequency of
  <literal role="S" typeofphrase="N"/>
  is by
  <param name="P"/>
  higher among the
  <fpa symbol="Y" number="pl"/>
  than in the whole collection. (There are 
  <param name="B"/>
  <ename symbol="E" number="pl"/>
  satisfying all the conditions.)
</fp>

<fp id="fp102" quantifier="AAI" numofant="1+" numofsuc="1+" numofcon="1+" show="yes">
  The relative frequency of
  <literal role="S" typeofphrase="N"/>
  is by 
  <param name="P"/>
  higher among the
  <fpa symbol="Y" number="pl"/>
  than in the whole collection. (There are
  <param name="B"/>
  <ename symbol="E" number="pl"/>
  satisfying all the conditions.)
  <fpa symbol="C"/>
</fp>


<fp id="fp103" quantifier="AAI" numofant="1+" numofsuc="1+" numofcon="0" show="yes">
  The relative frequency of
  <ename symbol="E" number="pl"/>
  that 
  <literal role="S" typeofphrase="V" number="pl"/>
  is by
  <param name="P"/>
  higher among the
  <fpa symbol="Y" number="pl"/>
  than in the whole collection. (There are
  <param name="B"/>
  <ename symbol="E" number="pl"/>
  satisfying all the conditions.)
</fp>

<fp id="fp104" quantifier="AAI" numofant="1+" numofsuc="1+" numofcon="1+" show="yes">
  The relative frequency of 
  <ename symbol="E" number="pl"/>
  that 
  <literal role="S" typeofphrase="V" number="pl"/>
  is by
  <param name="P"/>
  higher among the
  <fpa symbol="Y" number="pl"/>
  than in the whole collection. (There are
  <param name="B"/>
  <ename symbol="E" number="pl"/>
  satisfying all the conditions.)
  <fpa symbol="C"/>
</fp>


<!-- formulation patterns for Double Founded Implication -->

<fp id="fp201" quantifier="DFUI" numofant="1+" numofsuc="1+" numofcon="0" show="yes">
  From the total amount of
  <param name="T"/>
  <ename symbol="E" number="pl"/>
  , that
  <floatslot id="1" role="A" occno="first"/>
  <literal role="A" typeofphrase="V" number="pl"/>
  or
  <literal role="S" typeofphrase="V" number="pl"/>
  ,
  <param name="P"/>
  % (i.e.
  <param name="B"/>
  )
  <ename symbol="E" case="2" number="pl"/>
  <literal role="A" typeofphrase="V" number="pl"/>
  and simultaneously 
  <literal role="S" typeofphrase="V" number="pl"/>
  .
</fp>

<fp id="fp202" quantifier="DFUI" numofant="1+" numofsuc="1+" numofcon="1+" show="yes">
  From the total amount of
  <param name="T"/>
  <ename symbol="E" number="pl"/>
  , that
  <floatslot id="1" role="A" occno="first"/>
  <literal role="A" typeofphrase="V" number="pl"/>
  or
  <literal role="S" typeofphrase="V" number="pl"/>
  ,
  <param name="P"/>
  % (i.e.
  <param name="B"/>
  )
  <ename symbol="E" case="2" number="pl"/>
  <literal role="A" typeofphrase="V" number="pl"/>
  and simultaneously
  <literal role="S" typeofphrase="V" number="pl"/>
  .
  <fpa symbol="C"/>
</fp>


</formulationpatterns>
