=== BackupTheBerlios/reportasistent-svn/trunk/Setup/Setup_accessories/4ftAR2NL/dtd/ar2nl-1.2.dtd
<!-- AR2NL DTD 1.2 -->

<!-- This is DTD for data of the AR2NL system. 
     Please use the following formal public identifier to identify it:
     
     "-//LISp-Miner//DTD AR2NL 1.2//EN"
     
     If your document's top-level element is Formulation pattern,
     use this DOCTYPE declaration:
     
     <!DOCTYPE formulationpatterns PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
     	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">
	
     If your document's top-level element is Auxiliary symbol,
     use this DOCTYPE declaration:
     
     <!DOCTYPE auxiliarysymbols PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">
	
     If your document's top-level element is pattern for nouns,
     use this DOCTYPE declaration:
     
     <!DOCTYPE mnpatterns PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">
     
     If your document's top-level element is pattern for verbs,
     use this DOCTYPE declaration:
     
     <!DOCTYPE mvpatterns PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">
     
     If your document's top-level element is Entity,
     use this DOCTYPE declaration:
     
     <!DOCTYPE entitynames PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">
     
     If your document's top-level element is Elementary expression,
     use this DOCTYPE declaration:
     
     <!DOCTYPE elementaryexpressions PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
     	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">
	
     If your document's top-level element is file with language parameters,
     use this DOCTYPE declaration:
     
     <!DOCTYPE langparameters PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
     	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">

-->


<!-- entities -->

<!ENTITY % directive
           "case   (1|2|3|4|5|6|7|_|nom|gen|par|ess|tra|ine|ela|ill|ade|abl|all|abe|kom|ins) #IMPLIED
	    number (sg|pl|qpl|_)     #IMPLIED">

<!ENTITY % entity.symbol "symbol (E|Edefart|Edemonstr|Eid1|Eid2|Eindefart|Epers|Eptc0|Eptc1|Erel|EPtcPatternSuffix) #REQUIRED">

<!ENTITY % fpa.symbol "symbol (A|C|X|Y|Z) #REQUIRED">

<!ENTITY % role.symbol "role (A|S|C) #REQUIRED">

<!ENTITY % numofant "numofant CDATA #REQUIRED">
<!ENTITY % numofsuc "numofsuc CDATA #REQUIRED">
<!ENTITY % numofcon "numofcon CDATA #REQUIRED">

<!-- common elements -->

<!ELEMENT literal EMPTY>
<!ATTLIST literal %role.symbol;
		  typeofphrase (L|N|R|V|NA) #REQUIRED
                  %directive;
		  vderivation  (ptc)     #IMPLIED>

<!ELEMENT word (#PCDATA)>
<!ATTLIST word pattern CDATA #REQUIRED
               class (nominal|verb) #REQUIRED>

<!ELEMENT optionaltext (#PCDATA|choosetext)*>

<!ELEMENT choosetext (variant+)>

<!ELEMENT variant (#PCDATA)>

<!ELEMENT param EMPTY>
<!ATTLIST param name (B|P|T|N) #REQUIRED>

<!ELEMENT ename EMPTY>
<!ATTLIST ename %entity.symbol;
                %directive;>

<!ELEMENT floatslot EMPTY>
<!ATTLIST floatslot id CDATA #REQUIRED
                    %role.symbol;
		    occno (first|last) #REQUIRED>

<!-- formulation patterns -->

<!ELEMENT formulationpatterns (fp*)>

<!ELEMENT fp (#PCDATA|choosetext|ename|floatslot|fpa|literal|optionaltext|param)*>
<!ATTLIST fp id         ID      #REQUIRED
             quantifier (AAI|FUI|DFUI)   #REQUIRED
	     %numofant;
	     %numofsuc;
	     %numofcon;>

<!ELEMENT fpa EMPTY>
<!ATTLIST fpa %fpa.symbol;
              %directive;>

<!-- entities -->

<!ELEMENT entitynames (enamedata*)>

<!ELEMENT enamedata (#PCDATA|word)*>
<!ATTLIST enamedata id ID #REQUIRED
                    %entity.symbol;>

<!-- fpa - Formulation Patterns - Auxiliary -->

<!ELEMENT auxiliarysymbols (fpadata*)>

<!ELEMENT fpadata (#PCDATA|choosetext|ename|floatslot|fpa|literal|optionaltext|param)*>
<!ATTLIST fpadata id ID #REQUIRED
                  %fpa.symbol;
		  %numofant;
		  %numofsuc;
	          %numofcon;>

<!-- elementary expressions -->

<!ELEMENT elementaryexpressions (expression*)>

<!ELEMENT expression (mbattribute, meaning, (APinv|NPinv|VPinv)*, categories)>
<!ATTLIST expression id ID #REQUIRED>

<!ELEMENT mbattribute (#PCDATA)>

<!ELEMENT meaning (#PCDATA)>

<!ELEMENT VPinv (#PCDATA|float|param|word)*>
<!ELEMENT APinv (#PCDATA|float|param|word)*>
<!ELEMENT NPinv (#PCDATA|float|param|word)*>

<!ELEMENT categories (category+)>

<!ELEMENT category (value, meaning, adjphrase*, nounphrase*, NAF*, verbphrase*)>

<!ELEMENT value (#PCDATA)>

<!ELEMENT adjphrase (#PCDATA|APinv|float|param|word)*>
<!ATTLIST adjphrase relposition (R|L) #REQUIRED>

<!ELEMENT nounphrase (#PCDATA|float|NPinv|param|word)*>
<!ATTLIST nounphrase %directive;>

<!ELEMENT NAF (#PCDATA|nounphrase)*>

<!ELEMENT verbphrase (#PCDATA|float|param|ptcmod|ptcmodslot|VPinv|word)*>

<!ELEMENT float (#PCDATA)>
<!ATTLIST float id CDATA #REQUIRED>

<!ELEMENT ptcmod (#PCDATA|param|VPinv|word)*>
<!ATTLIST ptcmod id CDATA #REQUIRED>

<!ELEMENT ptcmodslot EMPTY>
<!ATTLIST ptcmodslot id CDATA #REQUIRED>

<!-- common elements for patterns in MN and MV -->

<!ELEMENT pattern (example, (endsegment*|(base, pl, qpl?, ptc, ptcpattern?)))>
<!ATTLIST pattern name   CDATA #REQUIRED>

<!ELEMENT endsegment (#PCDATA)>
<!ATTLIST endsegment case   (1|2|3|4|5|6|7|nom|gen|par|ess|tra|ine|ela|ill|ade|abl|all|abe|kom|ins) #IMPLIED
		     number (sg|pl) #REQUIRED>
<!ELEMENT base (#PCDATA)>
<!ELEMENT pl (#PCDATA)>
<!ELEMENT qpl (#PCDATA)>
<!ELEMENT ptc (#PCDATA)>
<!ATTLIST ptc recommended (yes|no) "yes">
<!ELEMENT ptcpattern (#PCDATA)>
<!ELEMENT example (#PCDATA)>

<!-- MN patterns -->

<!ELEMENT mnpatterns (pattern*)>

<!-- MV patterns -->

<!ELEMENT mvpatterns (pattern*)>

<!-- Language parameter -->

<!ELEMENT langparameters (langparam*)>

<!ELEMENT langparam EMPTY>
<!ATTLIST langparam name (conjunction|participle.position|decimal.point.symbol) #REQUIRED
	            value CDATA #REQUIRED>

=== BackupTheBerlios/reportasistent-svn/trunk/Setup/Setup_accessories/4ftAR2NL/_data/en/fpa.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE auxiliarysymbols PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">

<auxiliarysymbols>

<fpadata id="fpa1" symbol="X" numofant="1+" numofsuc="1+">
  <param name="P"/> % (i.e. <param name="B"/>) of the total of
  <param name="T"/>
</fpadata>

<fpadata id="fpa2" symbol="X" numofant="1+" numofsuc="1+">
  <param name="B"/> (i.e. <param name="P"/> %) of the total of
  <param name="T"/>
</fpadata>

<fpadata id="fpa3" symbol="X" numofant="1+" numofsuc="1+">
  <param name="B"/>, i.e. <param name="P"/> % of the total of
  <param name="T"/>
</fpadata>

<fpadata id="fpa4" symbol="Y" numofant="1+" numofsuc="1+">
  <ename symbol="E"/> that
  <literal role="A" typeofphrase="V" number="_"/>
</fpadata>

<fpadata id="fpa5" symbol="Y" numofant="1+" numofsuc="1+">
  <ename symbol="E"/>
  <literal role="A" typeofphrase="NA"/>
</fpadata>

<fpadata id="fpa6" symbol="Y" numofant="1+" numofsuc="1+">
  <ename symbol="E"/>
  <literal role="A" typeofphrase="R"/>
</fpadata>

<fpadata id="fpa7" symbol="Y" numofant="2+" numofsuc="1+">
  <literal role="A" typeofphrase="L"/>
  <ename symbol="E"/>
  <literal role="A" typeofphrase="R"/>
</fpadata>

<fpadata id="fpa8" symbol="Y" numofant="2+" numofsuc="1+">
  <literal role="A" typeofphrase="L"/>
  <ename symbol="E"/>
  <literal role="A" typeofphrase="NA"/>
</fpadata>

<fpadata id="fpa9" symbol="Y" numofant="1+" numofsuc="1+">
  <literal role="A" typeofphrase="L"/>
  <ename symbol="E"/>
</fpadata>

<fpadata id="fpa10" symbol="Z" numofant="1+" numofsuc="1+">
  <choosetext>
    <variant>This fact</variant>
    <variant>This hypothesis</variant>
    <variant>This rule</variant>
  </choosetext>
  is confirmed by <fpa symbol="X"/> observed <ename symbol="E" number="pl"/>.
</fpadata>

<fpadata id="fpa11" symbol="C" numofant="1+" numofsuc="1+" numofcon="1+">
<choosetext>
  <variant>This fact</variant>
  <variant>This hypothesis</variant>
  <variant>This rule</variant>
</choosetext>
is accepted
<choosetext>
 <variant> on condition that</variant>
 <variant> in this case:</variant>
 <variant> when</variant>
</choosetext>
 <ename symbol="Edefart"/>
 <ename symbol="E" number="sg"/>
 <literal role="C" typeofphrase="V"/>.
</fpadata>

</auxiliarysymbols>

=== BackupTheBerlios/reportasistent-svn/trunk/Setup/Setup_accessories/4ftAR2NL/_data/en/mv.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mvpatterns PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">

<mvpatterns>

<pattern name="v1">
  <example>walks</example>
  <base>s</base>
  <pl></pl>
  <ptc>ing</ptc>
</pattern>
<pattern name="v1g">
  <example>digs</example>
  <base>s</base>
  <pl></pl>
  <ptc>ging</ptc>
</pattern>
<pattern name="v1l">
  <example>travels</example>
  <base>s</base>
  <pl></pl>
  <ptc>ling</ptc>
</pattern>
<pattern name="v1t">
  <example>sits</example>
  <base>s</base>
  <pl></pl>
  <ptc>ting</ptc>
</pattern>
<pattern name="v2">
  <example>makes</example>
  <base>es</base>
  <pl>e</pl>
  <ptc>ing</ptc>
</pattern>
<pattern name="v2x">
  <example>teaches</example>
  <base>es</base>
  <pl></pl>
  <ptc>ing</ptc>
</pattern>
<pattern name="v3">
  <example>carries</example>
  <base>ies</base>
  <pl>y</pl>
  <ptc>ying</ptc>
</pattern>
<pattern name="v4">
  <example>has</example>
  <base>s</base>
  <pl>ve</pl>
  <ptc>ving</ptc>
</pattern>
<pattern name="v5">
  <example>is</example>
  <base>is</base>
  <pl>are</pl>
  <ptc></ptc>
</pattern>

</mvpatterns>

=== BackupTheBerlios/reportasistent-svn/trunk/Setup/Setup_accessories/4ftAR2NL/_data/fi/mv.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE mvpatterns PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">

<mvpatterns>
<!-- first participial form (active) -->
<pattern name="aa">
  <example>polttaa</example>
  <base>a</base>
  <pl>vat</pl>
  <ptc>va</ptc>
</pattern>
<pattern name="ee">
  <example>työskentelee-menee</example>
  <base>e</base>
  <pl>vät</pl>
  <ptc>vä</ptc>
  <ptcpattern>vä</ptcpattern>
</pattern>
<pattern name="ii">
  <example>kärsii</example>
  <base>i</base>
  <pl>vät</pl>
  <ptc>vä</ptc>
  <ptcpattern>vä</ptcpattern>
</pattern>
<pattern name="oo">
  <example>seisoo</example>
  <base>o</base>
  <pl>vat</pl>
  <ptc>va</ptc>
  <ptcpattern>va</ptcpattern>
</pattern>
<pattern name="uu">
  <example>ontuu-kuuluu-istuu</example>
  <base>u</base>
  <pl>vat</pl>
  <ptc>va</ptc>
  <ptcpattern>va</ptcpattern>
</pattern>
<pattern name="yy">
  <example>kysyy</example>
  <base>y</base>
  <pl>vät</pl>
  <ptc>vä</ptc>
  <ptcpattern>vä</ptcpattern>
</pattern>
<pattern name="ää">
  <example>käyttää</example>
  <base>ä</base>
  <pl>vät</pl>
  <ptc>vä</ptc>
  <ptcpattern>vä</ptcpattern>
</pattern>

<pattern name="koi">
  <example>tupakoi</example>
  <base></base>
  <pl>vat</pl>
  <ptc>va</ptc>
</pattern>
<pattern name="on">
  <example>on</example>
  <base>n</base>
  <pl>vat</pl>
  <ptc>leva</ptc>
</pattern>

<!-- first participial form (passive) -->
<pattern name="vs">
  <example>suorittaa</example>
  <base>a</base>
  <pl>vat</pl>
  <ptc>nut</ptc>
</pattern>

<pattern name="nut">
  <example>tupakoinut</example>
  <base>nut</base>
  <pl>neet</pl>
  <ptc>va</ptc>
</pattern>

<!-- short verbs -->
<pattern name="sai">
  <example>sai</example>
  <base>i</base>
  <pl>ivat</pl>
  <ptc>anut</ptc>
  <ptcpattern>nut</ptcpattern>
</pattern>
<pattern name="juo">
  <example>juo</example>
  <base></base>
  <pl>vat</pl>
  <ptc>ov</ptc>
</pattern>

<!-- negative -->
<pattern name="ei">
  <example>ei</example>
  <base></base>
  <pl>vät</pl>
  <ptc></ptc>
</pattern>


</mvpatterns>

=== BackupTheBerlios/reportasistent-svn/trunk/Setup/Setup_accessories/4ftAR2NL/data/fi/fpa.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE auxiliarysymbols PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">

<auxiliarysymbols>

<fpadata id="fpa1" symbol="X" numofant="1+" numofsuc="1+">
  <param name="P"/> % (eli <param name="B"/>) kaikkiaan
  <param name="T"/>:sta
</fpadata>

<fpadata id="fpa2" symbol="X" numofant="1+" numofsuc="1+">
  <param name="B"/> potilasta (eli <param name="P"/> %) kaikkiaan
  <param name="T"/>:sta
</fpadata>

<fpadata id="fpa3" symbol="X" numofant="1+" numofsuc="1+">
  <param name="B"/> potilasta eli <param name="P"/> % kaikkiaan
  <param name="T"/>:sta
</fpadata>

<fpadata id="fpa4" symbol="Y" numofant="1+" numofsuc="1+">
  <ename symbol="E" case="_" number="_"/>, <ename symbol="Eptc0" number="_"/> 
  <literal role="A" typeofphrase="V" number="_"/>, 
</fpadata>

<fpadata id="fpa5" symbol="Y" numofant="1+" numofsuc="1+">
  <ename symbol="E" number="pl"/>, joilla on
  <literal role="A" typeofphrase="N"/>,
</fpadata>

<!-- <fpadata id="fpa6" symbol="Y" numofant="1+" numofsuc="1+">
  fpa6<literal role="A" typeofphrase="R" number="pl"/>
  <ename symbol="E" number="pl"/>
</fpadata> -->  

<fpadata id="fpa7" symbol="Y" numofant="2" numofsuc="1+">
  <literal role="A" typeofphrase="R" number="pl" case="_"/>, 
  <literal role="A" typeofphrase="R" number="pl" case="_"/>
  <ename symbol="E" number="pl"/>
  
</fpadata>


<!-- <fpadata id="fpa8" symbol="Y" numofant="2+" numofsuc="1+">
  <literal role="A" typeofphrase="R" number="pl" case="_"/>
  <ename symbol="E" number="pl"/>, joilla on
  <literal role="A" typeofphrase="NA" number="pl" case="_"/>,
</fpadata>  -->

<!-- <fpadata id="fpa9" symbol="Y" numofant="1+" numofsuc="1+">
  fpa9<literal role="A" typeofphrase="L" number="_" case="_"/>
  <ename symbol="E"/>
</fpadata> --> 

<fpadata id="fpa10" symbol="Z" numofant="1+" numofsuc="1+">
  <choosetext>
    <variant>Tämän</variant>
    <variant>Tämän hypoteesin</variant>
    <variant>Tämän säännön</variant>
  </choosetext>
  toteuttaa <fpa symbol="X"/> havainnoidusta <ename symbol="E" case="ela" number="sg"/>.
</fpadata>

</auxiliarysymbols>

=== BackupTheBerlios/reportasistent-svn/trunk/Setup/Setup_accessories/4ftAR2NL/_data/cs/fpa.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE auxiliarysymbols PUBLIC "-//LISp-Miner//DTD AR2NL 1.2//EN"
	"http://lispminer.vse.cz/dtd/ar2nl-1.2.dtd">

<auxiliarysymbols>

<fpadata id="fpa1" symbol="X" numofant="1+" numofsuc="1+">
  <param name="P"/> % (konkrétně <param name="B"/>) z celkového počtu
  <param name="T"/>
</fpadata>

<fpadata id="fpa2" symbol="X" numofant="1+" numofsuc="1+">
  <param name="B"/> (tj. <param name="P"/> %) z celkového počtu
  <param name="T"/>
</fpadata>

<fpadata id="fpa3" symbol="X" numofant="1+" numofsuc="1+">
  <param name="B"/>, tj. <param name="P"/> % z celkového počtu
  <param name="T"/>
</fpadata>

<fpadata id="fpa4" symbol="Y" numofant="1+" numofsuc="1+">
  <ename symbol="E"/>,
  <ename symbol="Erel" number="_"/>
  <floatslot id="1" role="A" occno="first"/>
  <literal role="A" typeofphrase="V" number="_"/>,
</fpadata>

<fpadata id="fpa5" symbol="Y" numofant="1+" numofsuc="1+">
  <ename symbol="E"/>
  <literal role="A" typeofphrase="NA"/>
</fpadata>

<fpadata id="fpa7" symbol="Y" numofant="1+" numofsuc="1+">
  <ename symbol="E"/>
  <literal role="A" typeofphrase="R" case="_" number="_"/>
</fpadata>

<fpadata id="fpa8" symbol="Y" numofant="2+" numofsuc="1+">
  <ename symbol="E"/>
  <literal role="A" typeofphrase="NA"/>
  <literal role="A" typeofphrase="R" case="_" number="_"/>
</fpadata>

<fpadata id="fpa9" symbol="Y" numofant="2+" numofsuc="1+">
  <literal role="A" typeofphrase="L" case="_" number="_"/>
  <ename symbol="E"/>
  <literal role="A" typeofphrase="R" case="_" number="_"/>
</fpadata>

<fpadata id="fpa10" symbol="Y" numofant="2+" numofsuc="1+">
  <literal role="A" typeofphrase="L" case="_" number="_"/>
  <ename symbol="E"/>
  <literal role="A" typeofphrase="NA"/>
</fpadata>

<fpadata id="fpa11" symbol="Y" numofant="1+" numofsuc="1+">
  <literal role="A" typeofphrase="L" case="_" number="_"/>
  <ename symbol="E"/>
</fpadata>

<fpadata id="fpa12" symbol="Z" numofant="1+" numofsuc="1+">
  <choosetext>
    <variant>Tento fakt</variant>
    <variant>Tuto hypotézu</variant>
    <variant>Toto pravidlo</variant>
	<variant>Toto tvrzení</variant>
  </choosetext>
  potvrzuje <fpa symbol="X"/> <ename symbol="Eptc0" case="2" number="pl"/>
  <ename symbol="E" case="2" number="pl"/>.
</fpadata>

<fpadata id="fpa23" symbol="Y" numofant="2+" numofsuc="1+">
  <ename symbol="E"/>
  <literal role="A" typeofphrase="NA"/>,
  <ename symbol="Erel" number="_"/>
  <floatslot id="1" role="A" occno="last"/>
  <literal role="A" typeofphrase="V" number="_"/>
</fpadata>

<fpadata id="fpa24" symbol="C" numofant="1+" numofsuc="1+" numofcon="1+">
<choosetext>
  <variant>Tvrzení</variant>
  <variant>Hypotéza</variant>
  <variant>Tento fakt</variant>
</choosetext>
platí
<choosetext>
 <variant>za těchto podmínek:</variant>
 <variant>v případě, že</variant>
 <variant>, když</variant>
</choosetext>
 <ename symbol="E" case="1" number="sg"/>
 <literal role="C" typeofphrase="V"/>.
</fpadata>


</auxiliarysymbols>
