<?xml version="1.0" encoding="windows-1250" ?>

<!DOCTYPE report [

<!ELEMENT report ( chapter | include )* >
<!ATTLIST report title CDATA #IMPLIED >
<!ATTLIST report subtitle CDATA #IMPLIED >
<!ATTLIST report author CDATA #IMPLIED >
<!ATTLIST report id ID #REQUIRED >

<!ELEMENT chapter ( (paragraph | include | active_element)*, chapter* ) > <!--nejprve texty, pak vnorene kapitoly -->
<!ATTLIST chapter title CDATA #REQUIRED >
<!ATTLIST chapter id ID #REQUIRED >

<!ELEMENT active_element ( params, filter, output )>
<!ATTLIST active_element type CDATA #REQUIRED >
<!ATTLIST active_element source CDATA #REQUIRED >
<!ATTLIST active_element id ID #REQUIRED >

<!ELEMENT params EMPTY >

<!ELEMENT filter (selection+) >
<!ATTLIST filter type CDATA #REQUIRED>
	
<!ELEMENT selection EMPTY >
<!ATTLIST selection id CDATA #REQUIRED>	<!-- odkaz na data ze zasuvky nikoli ID prvku - mozna prejmenovat --> 

<!ELEMENT output (transformation+) >

<!ELEMENT transformation EMPTY >
<!ATTLIST transformation file CDATA #REQUIRED>
	
<!ELEMENT include EMPTY >
<!ATTLIST include file CDATA #REQUIRED >
<!ATTLIST include id ID #REQUIRED >

<!ELEMENT paragraph ( graph | table | text )* >
<!ATTLIST paragraph style CDATA #IMPLIED >
<!ATTLIST paragraph id ID #REQUIRED >

<!ELEMENT text ( #PCDATA | br | tab )* >
<!ATTLIST text style CDATA #IMPLIED >
<!ATTLIST text id ID #REQUIRED >

<!ELEMENT tab EMPTY > <!-- do textu vlozi tabulator -->

<!ELEMENT br EMPTY > <!-- do textu vlozi prechod na novy radek - nikoliv konec odstavce -->

<!ELEMENT graph ( categories? , chart+ ) >
<!ATTLIST graph title CDATA #IMPLIED >
<!ATTLIST graph charttype CDATA #REQUIRED >	<!-- napr: xlLine, xlPie, xlBarStacked -->
	<!-- kompletni seznam pro OfficeXP k nalezeni na http://msdn.microsoft.com/library/en-us/vbagr10/html/grprocharttype.asp -->
<!ATTLIST graph showlegend (true | false) "false" >
<!ATTLIST graph height CDATA #IMPLIED >	<!-- nasobek sirky strnaky -->
<!ATTLIST graph width CDATA #IMPLIED >	<!-- nasobek sirky strnaky -->	
<!ATTLIST graph id ID #REQUIRED >


<!ELEMENT categories ( category+ ) >
<!ATTLIST categories id ID #REQUIRED >

<!ELEMENT category EMPTY >
<!ATTLIST category title CDATA #REQUIRED >
<!ATTLIST category id ID #REQUIRED >

<!ELEMENT chart ( value+ ) >
<!ATTLIST chart title CDATA #IMPLIED >
<!ATTLIST chart id ID #REQUIRED >

<!ELEMENT value EMPTY >
<!ATTLIST value value CDATA #REQUIRED >	<!-- cislo nebo cislo s procentama -->
<!ATTLIST value id ID #REQUIRED >

<!ELEMENT table ( tr+ ) >
<!ATTLIST table cols CDATA #REQUIRED >
<!ATTLIST table rows CDATA #REQUIRED >
<!ATTLIST table borderwidth CDATA "0" >	<!-- default borderwidth=0 -->
<!ATTLIST table id ID #REQUIRED >

<!ELEMENT tr ( td+ ) >
<!ATTLIST tr id ID #REQUIRED >

<!ELEMENT td ( text? ) >
<!ATTLIST td colspan CDATA #IMPLIED >
<!ATTLIST td rowspan CDATA #IMPLIED >
<!ATTLIST td bgcolor CDATA #IMPLIED >	<!-- pouze kody #RRGGBB pojmenovane barvy nejsou podporovany -->
<!ATTLIST td id ID #REQUIRED >


]>


<report title="EVROPSKÝ REGION PRAHA 2004" subtitle="Analytická otázka èíslo 3 (MFF 2004/2005)" author="Jan Dìdek" id="report1">

	
<chapter title="tady je nas prvni aktivni prvek" id="ch_aktivni1">
	<active_element type="hyp_4ft" source="honzova_metabaze" id="hyp_4ft1">
		<params/>
	
		<filter type="simple">
			<selection id="hyp1"/>
			<selection id="hyp3"/>
		</filter>
	
		<output>
			<transformation file="../XML/4ft_generuj1.xsl"/>
			<transformation file="../XML/4ft_generuj1.xsl"/>
		</output>
	</active_element>
</chapter>

<chapter title="Životní hodnoty, Modernizace a elity, Zpùsob vnímání transformaèního procesu" id="chapter3">
	<paragraph style="Normální" id="paragraph5">
		<text id="text7">Výsledky v analytické zprávì odpovídají </text>
		<text id="text9" style="Silné">Reprezentativnímu výbìrovému souboru</text>
		<text id="text11"> respondentù. Na kompletní data jsem též analyzoval a výsledky byly podobné,
vìtšinou vycházely o ménì silné vztahy - pravdìpodobnì díky chybìjícím informacím.</text>
	</paragraph>
</chapter>

<chapter title="Zkoumané atributy" id="chapter15">
	<paragraph id="paragraph17">
		 <text id="text19">V této kapitole popíšu, kterými atributy jsem se zabýval.</text>
	</paragraph>
	
	<chapter title="Odvozený atribut „Zpùsob vnímání transformaèního procesu“" id="chapter22">
		<paragraph id="paragraph24">
			<text id="text26">Vznikl z atributù:</text>
			<table cols="2" rows="4" borderwidth="1" id="table28">
				<tr id="tr30">
					<td id="td32"><text id="text33">znak</text></td>	<td id="td35"><text id="text36">Popis</text></td>
				</tr>
				<tr id="tr39">
					<td id="td41"><text id="text42">z5</text></td>
					<td id="td44"><text id="text45">Bude se podle Vašeho názoru v nejbližších letech v naší zemi životní úroveò vìtšiny obyvatel zlepšovat?</text></td>
				</tr>
				<tr id="tr48">
					<td id="td50"><text id="text51">z6</text></td>
					<td id="td53"><text id="text54">Mùže se u nás v blízké budoucnosti prohlubovat problém chudoby?</text></td>
				</tr>
				<tr id="tr57">
					<td id="td59"><text id="text60">z7</text></td>
					<td id="td62"><text id="text63">Je souèasná ekonomická situace pro Vaši domácnost výhodná?</text></td>
				</tr>
			</table>
		</paragraph>

		<paragraph id="paragraph68">
			<text id="text70">Hodnoty:</text>
			<table rows="7" cols="6" borderwidth="1" id="table72">
				<tr id="tr74">
					<td rowspan="2" id="td76"><text id="text77">Typ</text></td>
					<td colspan="3" id="td79"><text id="text80">Hodnota atributu</text></td>
					<td rowspan="2" id="td82"><text id="text83">Vìcný význam - název typu</text></td>
					<td rowspan="2" id="td85"><text id="text86">Zjištìná relativní èetnost
pro 2672 respondentù</text></td>
				</tr>
				<tr id="tr89">
					<td id="td91"></td><!-- prazdne sloupce pro zjednoduseni ???span atributu -->
					<td id="td94"><text id="text95">z5</text></td>	<td id="td97"><text id="text98">z6</text></td>	<td id="td100"><text id="text101">z7</text></td>
					<td id="td103"></td><!-- prazdne sloupce pro zjednoduseni ???span atributu -->
					<td id="td106"></td><!-- prazdne sloupce pro zjednoduseni ???span atributu -->
				</tr>
				<tr id="tr110">
					<td id="td112"><text id="text113">1</text></td>
					<td id="td115"><text id="text116">1</text></td>
					<td id="td118"><text id="text119">1</text></td>
					<td id="td121"><text id="text122">1</text></td>
					<td id="td124"><text id="text125">angažovaný liberál</text></td>
					<td id="td127"><text id="text128">12,3 %</text></td>
				</tr>
				<tr id="tr131">
					<td id="td133"><text id="text134">2</text></td>
					<td id="td136"><text id="text137">1</text></td>
					<td id="td139"><text id="text140">1</text></td>
					<td id="td142"><text id="text143">2</text></td>
					<td id="td145"><text id="text146">realistický optimista</text></td>
					<td id="td148"><text id="text149">9,7 %</text></td>
				</tr>
				<tr id="tr152">
					<td id="td154"><text id="text155">3</text></td>
					<td id="td157"><text id="text158">1</text></td>
					<td id="td160"><text id="text161">2</text></td>
					<td id="td163"><text id="text164">1</text></td>
					<td id="td166"><text id="text167">èlovìk této doby</text></td>
					<td id="td169"><text id="text170">24,9 %</text></td>
				</tr>
				<tr id="tr173">
					<td id="td175"><text id="text176">6</text></td>
					<td id="td178"><text id="text179">2</text></td>
					<td id="td181"><text id="text182">1</text></td>
					<td id="td184"><text id="text185">2</text></td>
					<td id="td187"><text id="text188">posel špatných zpráv</text></td>
					<td id="td190"><text id="text191">26,8 %</text></td>
				</tr>
				<tr id="tr194">
					<td id="td196"><text id="text197">7</text></td>
					<td id="td199"><text id="text200">1</text></td>
					<td id="td202"><text id="text203">2</text></td>
					<td id="td205"><text id="text206">2</text></td>
					<td id="td208"><text id="text209">vizionáø</text></td>
					<td id="td211"><text id="text212">10,2 %</text></td>
				</tr>
			</table>
		</paragraph>
		<chapter title="Èetnosti jednotlivých typù:" id="chapter217">
			<paragraph id="paragraph219">
				<table rows="23" cols="7" borderwidth="1" id="table221">
					<tr id="tr223">
						<td id="td225"></td>
						<td id="td227"><text id="text228">angažovaný liberál</text></td>
						<td id="td230"><text id="text231">realistický optimista</text></td>
						<td id="td233"><text id="text234">èlovìk této doby</text></td>
						<td id="td236"><text id="text237">posel špatných zpráv</text></td>
						<td id="td239"><text id="text240">vizionáø</text></td>
						<td id="td242"><text id="text243">ostatní</text></td>						
					</tr>

<tr id="tr246"><td id="td247"><text id="text248">Praha 1</text></td> <td bgcolor="#FFCDCD" id="td250"><text id="text252">20</text></td> <td bgcolor="#FFE6E6" id="td254"><text id="text256">10</text></td> <td bgcolor="#FFCDCD" id="td258"><text id="text260">20</text></td> <td bgcolor="#FFEDED" id="td262"><text id="text264">7</text></td> <td bgcolor="#FFDCDC" id="td266"><text id="text268">14</text></td> <td bgcolor="#FFD2D2" id="td270"><text id="text272">18</text></td></tr>
<tr id="tr274"><td id="td275"><text id="text276">Praha 2</text></td> <td bgcolor="#FFD4D4" id="td278"><text id="text280">17</text></td> <td bgcolor="#FFD2D2" id="td282"><text id="text284">18</text></td> <td bgcolor="#FFA9A9" id="td286"><text id="text288">34</text></td> <td bgcolor="#FFDCDC" id="td290"><text id="text292">14</text></td> <td bgcolor="#FFB6B6" id="td294"><text id="text296">29</text></td> <td bgcolor="#FFD7D7" id="td298"><text id="text300">16</text></td></tr>
<tr id="tr302"><td id="td303"><text id="text304">Praha 3</text></td> <td bgcolor="#FFBBBB" id="td306"><text id="text308">27</text></td> <td bgcolor="#FFDCDC" id="td310"><text id="text312">14</text></td> <td bgcolor="#FFC7C7" id="td314"><text id="text316">22</text></td> <td bgcolor="#FFCACA" id="td318"><text id="text320">21</text></td> <td bgcolor="#FF6868" id="td322"><text id="text324">60</text></td> <td bgcolor="#FFB3B3" id="td326"><text id="text328">30</text></td></tr>
<tr id="tr330"><td id="td331"><text id="text332">Praha 4</text></td> <td bgcolor="#FFB1B1" id="td334"><text id="text336">31</text></td> <td bgcolor="#FFB8B8" id="td338"><text id="text340">28</text></td> <td bgcolor="#FF0000" id="td342"><text id="text344">101</text></td> <td bgcolor="#FFBBBB" id="td346"><text id="text348">27</text></td> <td bgcolor="#FF4747" id="td350"><text id="text352">73</text></td> <td bgcolor="#FF8181" id="td354"><text id="text356">50</text></td></tr>
<tr id="tr358"><td id="td359"><text id="text360">Praha 5</text></td> <td bgcolor="#FFDCDC" id="td362"><text id="text364">14</text></td> <td bgcolor="#FFCFCF" id="td366"><text id="text368">19</text></td> <td bgcolor="#FFA2A2" id="td370"><text id="text372">37</text></td> <td bgcolor="#FFD9D9" id="td374"><text id="text376">15</text></td> <td bgcolor="#FF7979" id="td378"><text id="text380">53</text></td> <td bgcolor="#FFA7A7" id="td382"><text id="text384">35</text></td></tr>
<tr id="tr386"><td id="td387"><text id="text388">Praha 6</text></td> <td bgcolor="#FFBDBD" id="td390"><text id="text392">26</text></td> <td bgcolor="#FFC2C2" id="td394"><text id="text396">24</text></td> <td bgcolor="#FF6262" id="td398"><text id="text400">62</text></td> <td bgcolor="#FFCDCD" id="td402"><text id="text404">20</text></td> <td bgcolor="#FF6F6F" id="td406"><text id="text408">57</text></td> <td bgcolor="#FFA2A2" id="td410"><text id="text412">37</text></td></tr>
<tr id="tr414"><td id="td415"><text id="text416">Praha 7</text></td> <td bgcolor="#FFF2F2" id="td418"><text id="text420">5</text></td> <td bgcolor="#FFD7D7" id="td422"><text id="text424">16</text></td> <td bgcolor="#FFAEAE" id="td426"><text id="text428">32</text></td> <td bgcolor="#FFCFCF" id="td430"><text id="text432">19</text></td> <td bgcolor="#FFC7C7" id="td434"><text id="text436">22</text></td> <td bgcolor="#FFE1E1" id="td438"><text id="text440">12</text></td></tr>
<tr id="tr442"><td id="td443"><text id="text444">Praha 8</text></td> <td bgcolor="#FF7C7C" id="td446"><text id="text448">52</text></td> <td bgcolor="#FFCFCF" id="td450"><text id="text452">19</text></td> <td bgcolor="#FF5656" id="td454"><text id="text456">67</text></td> <td bgcolor="#FFDCDC" id="td458"><text id="text460">14</text></td> <td bgcolor="#FF6868" id="td462"><text id="text464">60</text></td> <td bgcolor="#FF8181" id="td466"><text id="text468">50</text></td></tr>
<tr id="tr470"><td id="td471"><text id="text472">Praha 9</text></td> <td bgcolor="#FFE3E3" id="td474"><text id="text476">11</text></td> <td bgcolor="#FFF0F0" id="td478"><text id="text480">6</text></td> <td bgcolor="#FFACAC" id="td482"><text id="text484">33</text></td> <td bgcolor="#FFD7D7" id="td486"><text id="text488">16</text></td> <td bgcolor="#FFB3B3" id="td490"><text id="text492">30</text></td> <td bgcolor="#FFE8E8" id="td494"><text id="text496">9</text></td></tr>
<tr id="tr498"><td id="td499"><text id="text500">Praha 10</text></td> <td bgcolor="#FFAEAE" id="td502"><text id="text504">32</text></td> <td bgcolor="#FFACAC" id="td506"><text id="text508">33</text></td> <td bgcolor="#FF5151" id="td510"><text id="text512">69</text></td> <td bgcolor="#FFAEAE" id="td514"><text id="text516">32</text></td> <td bgcolor="#FF3F3F" id="td518"><text id="text520">76</text></td> <td bgcolor="#FFACAC" id="td522"><text id="text524">33</text></td></tr>
<tr id="tr526"><td id="td527"><text id="text528">Praha 11</text></td> <td bgcolor="#FFAEAE" id="td530"><text id="text532">32</text></td> <td bgcolor="#FFC2C2" id="td534"><text id="text536">24</text></td> <td bgcolor="#FF9292" id="td538"><text id="text540">43</text></td> <td bgcolor="#FFC0C0" id="td542"><text id="text544">25</text></td> <td bgcolor="#FF7474" id="td546"><text id="text548">55</text></td> <td bgcolor="#FFA4A4" id="td550"><text id="text552">36</text></td></tr>
<tr id="tr554"><td id="td555"><text id="text556">Praha 12</text></td> <td bgcolor="#FFCFCF" id="td558"><text id="text560">19</text></td> <td bgcolor="#FFD7D7" id="td562"><text id="text564">16</text></td> <td bgcolor="#FFA2A2" id="td566"><text id="text568">37</text></td> <td bgcolor="#FFC2C2" id="td570"><text id="text572">24</text></td> <td bgcolor="#FF7E7E" id="td574"><text id="text576">51</text></td> <td bgcolor="#FFC5C5" id="td578"><text id="text580">23</text></td></tr>
<tr id="tr582"><td id="td583"><text id="text584">Praha 13</text></td> <td bgcolor="#FFF7F7" id="td586"><text id="text588">3</text></td> <td bgcolor="#FFF5F5" id="td590"><text id="text592">4</text></td> <td bgcolor="#FF9292" id="td594"><text id="text596">43</text></td> <td bgcolor="#FFD7D7" id="td598"><text id="text600">16</text></td> <td bgcolor="#FFB6B6" id="td602"><text id="text604">29</text></td> <td bgcolor="#FFBBBB" id="td606"><text id="text608">27</text></td></tr>
<tr id="tr610"><td id="td611"><text id="text612">Praha 14</text></td> <td bgcolor="#FFD9D9" id="td614"><text id="text616">15</text></td> <td bgcolor="#FFF2F2" id="td618"><text id="text620">5</text></td> <td bgcolor="#FFD2D2" id="td622"><text id="text624">18</text></td> <td bgcolor="#FFEDED" id="td626"><text id="text628">7</text></td> <td bgcolor="#FFA2A2" id="td630"><text id="text632">37</text></td> <td bgcolor="#FFDEDE" id="td634"><text id="text636">13</text></td></tr>
<tr id="tr638"><td id="td639"><text id="text640">Praha 15</text></td> <td bgcolor="#FFDCDC" id="td642"><text id="text644">14</text></td> <td bgcolor="#FFE3E3" id="td646"><text id="text648">11</text></td> <td bgcolor="#FFE6E6" id="td650"><text id="text652">10</text></td> <td bgcolor="#FFEBEB" id="td654"><text id="text656">8</text></td> <td bgcolor="#FFBBBB" id="td658"><text id="text660">27</text></td> <td bgcolor="#FFD7D7" id="td662"><text id="text664">16</text></td></tr>
<tr id="tr666"><td id="td667"><text id="text668">Praha 16- Radotín</text></td> <td bgcolor="#FFE3E3" id="td670"><text id="text672">11</text></td> <td bgcolor="#FFD7D7" id="td674"><text id="text676">16</text></td> <td bgcolor="#FF7979" id="td678"><text id="text680">53</text></td> <td bgcolor="#FFE6E6" id="td682"><text id="text684">10</text></td> <td bgcolor="#FFB6B6" id="td686"><text id="text688">29</text></td> <td bgcolor="#FFC0C0" id="td690"><text id="text692">25</text></td></tr>
<tr id="tr694"><td id="td695"><text id="text696">Praha 17- Øepy</text></td> <td bgcolor="#FFC5C5" id="td698"><text id="text700">23</text></td> <td bgcolor="#FFD2D2" id="td702"><text id="text704">18</text></td> <td bgcolor="#FF9292" id="td706"><text id="text708">43</text></td> <td bgcolor="#FFCACA" id="td710"><text id="text712">21</text></td> <td bgcolor="#FF7474" id="td714"><text id="text716">55</text></td> <td bgcolor="#FFA4A4" id="td718"><text id="text720">36</text></td></tr>
<tr id="tr722"><td id="td723"><text id="text724">Praha 18- Letòany</text></td> <td bgcolor="#FFD9D9" id="td726"><text id="text728">15</text></td> <td bgcolor="#FFDEDE" id="td730"><text id="text732">13</text></td> <td bgcolor="#FFCACA" id="td734"><text id="text736">21</text></td> <td bgcolor="#FFD4D4" id="td738"><text id="text740">17</text></td> <td bgcolor="#FFCFCF" id="td742"><text id="text744">19</text></td> <td bgcolor="#FFC5C5" id="td746"><text id="text748">23</text></td></tr>
<tr id="tr750"><td id="td751"><text id="text752">Praha 19- Kbely</text></td> <td bgcolor="#FFEBEB" id="td754"><text id="text756">8</text></td> <td bgcolor="#FFD2D2" id="td758"><text id="text760">18</text></td> <td bgcolor="#FFCFCF" id="td762"><text id="text764">19</text></td> <td bgcolor="#FFD9D9" id="td766"><text id="text768">15</text></td> <td bgcolor="#FFB3B3" id="td770"><text id="text772">30</text></td> <td bgcolor="#FFD9D9" id="td774"><text id="text776">15</text></td></tr>
<tr id="tr778"><td id="td779"><text id="text780">Praha 20- H. Poèernice</text></td> <td bgcolor="#FFEBEB" id="td782"><text id="text784">8</text></td> <td bgcolor="#FFD9D9" id="td786"><text id="text788">15</text></td> <td bgcolor="#FFDCDC" id="td790"><text id="text792">14</text></td> <td bgcolor="#FFDEDE" id="td794"><text id="text796">13</text></td> <td bgcolor="#FFC0C0" id="td798"><text id="text800">25</text></td> <td bgcolor="#FFCACA" id="td802"><text id="text804">21</text></td></tr>
<tr id="tr806"><td id="td807"><text id="text808">Praha 21- Újezd</text></td> <td bgcolor="#FFF2F2" id="td810"><text id="text812">5</text></td> <td bgcolor="#FFF2F2" id="td814"><text id="text816">5</text></td> <td bgcolor="#FFCACA" id="td818"><text id="text820">21</text></td> <td bgcolor="#FFFCFC" id="td822"><text id="text824">1</text></td> <td bgcolor="#FFBBBB" id="td826"><text id="text828">27</text></td> <td bgcolor="#FFBBBB" id="td830"><text id="text832">27</text></td></tr>
<tr id="tr834"><td id="td835"><text id="text836">Praha 22- Uhøínìves</text></td> <td bgcolor="#FFF7F7" id="td838"><text id="text840">3</text></td> <td bgcolor="#FFEBEB" id="td842"><text id="text844">8</text></td> <td bgcolor="#FFDEDE" id="td846"><text id="text848">13</text></td> <td bgcolor="#FFDEDE" id="td850"><text id="text852">13</text></td> <td bgcolor="#FFD9D9" id="td854"><text id="text856">15</text></td> <td bgcolor="#FFDEDE" id="td858"><text id="text860">13</text></td></tr>


				</table>
			</paragraph>
		</chapter>

	</chapter>

	<chapter title="Jak s vìkem klesá poèet lidí této doby:" id="chapter866">
		<paragraph id="paragraph868">
			<graph title="Èlovìk této doby X vìk" showlegend="false" charttype="xlColumnClustered" id="graph870">
				<categories id="categories872">
					<category title="15-24" id="category874"></category>
					<category title="25-34" id="category876"></category>
					<category title="35-44" id="category878"></category>
					<category title="45-54" id="category880"></category>
					<category title="55-64" id="category882"></category>
					<category title="65-74" id="category884"></category>
					<category title="75-84" id="category886"></category>
					<category title="85-94" id="category888"></category>
				</categories>

				<chart title="graf1" id="chart891">
					<value value="100%" id="value893"></value>
					<value value="88%" id="value895"></value>
					<value value="93%" id="value897"></value>
					<value value="72%" id="value899"></value>
					<value value="74%" id="value901"></value>
					<value value="46%" id="value903"></value>
					<value value="40%" id="value905"></value>
					<value value="63%" id="value907"></value>
				</chart>
			</graph>
			<text id="text911">
Hodnoty jsou normalizované vzhledem k poètu zástupcù v jednotlivých kategoriích.
Poslední kategorie je pravdìpodobnì zkreslená díky malému poètu zástupcù.</text>
		</paragraph>
	</chapter>

</chapter>

<chapter title="Analytické výsledky" id="chapter916">
	<chapter title="Dùležitost práce v závislosti na vìku dotázaných" id="chapter918">
		<paragraph id="paragraph920">
			<graph showlegend="false" charttype="xl3DColumnClustered" height="0,60" id="graph922">
				<categories id="categories924">
					<category title="15-24" id="category926"></category>
					<category title="25-34" id="category928"></category>
					<category title="35-44" id="category930"></category>
					<category title="45-54" id="category932"></category>
					<category title="55-64" id="category934"></category>
					<category title="65-74" id="category936"></category>
					<category title="75-84" id="category938"></category>
					<category title="85-94" id="category940"></category>
				</categories>

				<chart title="graf2" id="chart943">
					<value value="71%" id="value945"></value>
					<value value="94%" id="value947"></value>
					<value value="100%" id="value949"></value>
					<value value="96%" id="value951"></value>
					<value value="82%" id="value953"></value>
					<value value="34%" id="value955"></value>
					<value value="39%" id="value957"></value>
					<value value="71%" id="value959"></value>
				</chart>
			</graph>
			<text id="text963">
bodové hodnocení:

velmi dùležitá +4, dost dùležitá +3, nepøíliš dùležitá -3, vùbec nedùležitá -4

Hodnoty jsou normalizované vzhledem k poètu zástupcù v jednotlivých kategoriích.</text>
		</paragraph>
	</chapter>
	
	<chapter title="Muži ve vìku 61-70 let s Vysokou školou považují politiku zadùležitou." id="chapter967">
		<paragraph id="paragraph969"><text id="text970">A:	29</text></paragraph>
		<paragraph id="paragraph972"><text id="text973">B:	14</text></paragraph>
		<paragraph id="paragraph975"><text id="text976">C:	628</text></paragraph>
		<paragraph id="paragraph978"><text id="text979">D:	2627</text></paragraph>
		<paragraph id="paragraph981"><text id="text982">confidence a/(a+b):	0,674</text></paragraph>
		<paragraph id="paragraph984"><text id="text985">above average a(a+b+c+d) / (a+b)(a+c):	3,385</text></paragraph>
		<paragraph id="paragraph987">
			<graph title="confidence: 0,674" showlegend="false" charttype="xlPie" width="0,20" height="0,20" id="graph989">
				<chart id="chart991">
					<value value="0,674" id="value993"></value>
					<value value="0,326" id="value995"></value>
				</chart>			
			</graph>
			
			<table rows="4" cols="4" borderwidth="1" id="table999">
					<tr id="tr1001">
						<td id="td1003"></td>
						<td id="td1005"><text id="text1006">antecedent</text></td>
						<td id="td1008"><text id="text1009">not antecedent</text></td>
						<td id="td1011"><text id="text1012">souèet</text></td>						
					</tr>
					<tr id="tr1015">
						<td id="td1017"><text id="text1018">succedent</text></td>
						<td bgcolor="#FFE0E0" id="td1020"><text id="text1021">29</text></td>
						<td bgcolor="#FFF0F0" id="td1023"><text id="text1024">14</text></td>
						<td bgcolor="#FFD0D0" id="td1026"><text id="text1027">43</text></td>

					</tr>
					<tr id="tr1030">
						<td id="td1032"><text id="text1033">not succedent</text></td>
						<td bgcolor="#FF8080" id="td1035"><text id="text1036">628</text></td>
						<td bgcolor="#FF4040" id="td1038"><text id="text1039">2627</text></td>
						<td bgcolor="#FF0000" id="td1041"><text id="text1042">3255</text></td>
					</tr>
					<tr id="tr1045">
						<td id="td1047"><text id="text1048">souèet</text></td>						
						<td bgcolor="#FF7070" id="td1050"><text id="text1051">657</text></td>
						<td bgcolor="#FF3030" id="td1053"><text id="text1054">2641</text></td>
						<td id="td1056"><text id="text1057">3298</text></td>
					</tr>
			</table>

			<graph title="4FT table" showlegend="true" charttype="xlColumnStacked" width="0,75" height="1,4" id="graph1061">
				<categories id="categories1063">
					<category title="succedent" id="category1065"></category>
					<category title="not succedent" id="category1067"></category>
				</categories>
				<chart title="antecend" id="chart1070">
					<value value="29" id="value1072"></value>
					<value value="14" id="value1074"></value>
				</chart>			
				<chart title="not antecend" id="chart1077">
					<value value="628" id="value1079"></value>
					<value value="2627" id="value1081"></value>
				</chart>			
			</graph>

			<graph title="4FT table 2nd-try" showlegend="true" charttype="xl3DColumn" height="0,4" id="graph1085">
				<categories id="categories1087">
					<category title="succedent" id="category1089"></category>
					<category title="not succedent" id="category1091"></category>
				</categories>
				<chart title="antecend" id="chart1094">
					<value value="29" id="value1096"></value>
					<value value="14" id="value1098"></value>
				</chart>			
				<chart title="not antecend" id="chart1101">
					<value value="628" id="value1103"></value>
					<value value="2627" id="value1105"></value>
				</chart>			
			</graph>
		</paragraph>
	</chapter>

</chapter>
<!--
<include file="../XML/include_doc.doc" id="include1"/>
-->
</report>
