<?xml version="1.0" encoding="windows-1250" ?>
<!DOCTYPE active_list[
  
<!ELEMENT active_list ((hyp_4ft*, hyp_sd4ft*, hyp_kl*, hyp_sdkl*, hyp_cf*, hyp_sdcf*, category*, ti_cedent*, ti_attribute*, attribute*, bool_cedent*, CF_cedent*, KL_cedent*, hyp_kl*, task*, quantifier*, ferda_box*)*)>


<!-- Active elements "Analyzed data" -->

  

<!-- Active elements "Task" -->

  <!ELEMENT task EMPTY >
  <!ATTLIST task 	id ID #REQUIRED
			            db_name CDATA #REQUIRED
			            matrix_name CDATA #REQUIRED
			            task_name CDATA #REQUIRED
			            task_type CDATA #REQUIRED
			            gen_state CDATA #REQUIRED
  	              gen_total_time CDATA #REQUIRED
	                gen_start_time CDATA #REQUIRED
  			          num_hyp CDATA #REQUIRED
  			          num_tests CDATA #REQUIRED >
              
 

<!-- Active elements Cedents -->

  <!ELEMENT KL_cedent (sub_KL_cedent*)>
  <!ATTLIST KL_cedent 	id ID #REQUIRED
			db_name CDATA #REQUIRED
			matrix_name CDATA #REQUIRED
			task_name CDATA #REQUIRED
			task_type CDATA #REQUIRED
			cedent_type CDATA #REQUIRED
			sub_cedent_cnt CDATA #REQUIRED>
  <!ELEMENT sub_KL_cedent (KL_literal*)>
  <!ATTLIST sub_KL_cedent name CDATA #REQUIRED
			  literal_cnt CDATA #REQUIRED
			  length CDATA #REQUIRED>
  <!ELEMENT KL_literal EMPTY>
  <!ATTLIST KL_literal underlying_attribute CDATA #REQUIRED
		       category_cnt CDATA #REQUIRED>



  <!ELEMENT CF_cedent (sub_CF_cedent*)>
  <!ATTLIST CF_cedent 	id ID #REQUIRED
			db_name CDATA #REQUIRED
			matrix_name CDATA #REQUIRED
			task_name CDATA #REQUIRED
			task_type CDATA #REQUIRED
			cedent_type CDATA #REQUIRED
			sub_cedent_cnt CDATA #REQUIRED>
  <!ELEMENT sub_CF_cedent (CF_literal*)>
  <!ATTLIST sub_CF_cedent name CDATA #REQUIRED
			  literal_cnt CDATA #REQUIRED
			  length CDATA #REQUIRED>
  <!ELEMENT CF_literal EMPTY>
  <!ATTLIST CF_literal underlying_attribute CDATA #REQUIRED
		       category_cnt CDATA #REQUIRED>


<!-- Toto je puvodni implementace, bylo predelano pouze na dilci cedenty

  <!ELEMENT bool_cedent (sub_bool_cedent*)>
  <!ATTLIST bool_cedent id ID #REQUIRED
			db_name CDATA #REQUIRED
			matrix_name CDATA #REQUIRED
			task_name CDATA #REQUIRED
			task_type CDATA #REQUIRED
			cedent_type CDATA #REQUIRED
			sub_cedent_cnt CDATA #REQUIRED>
  <!ELEMENT sub_bool_cedent (literal*)>
  <!ATTLIST sub_bool_cedent name CDATA #REQUIRED
			    literal_cnt CDATA #REQUIRED
			    length CDATA #REQUIRED>
  <!ELEMENT literal EMPTY>
  <!ATTLIST literal underlying_attribute CDATA #REQUIRED
		    category_cnt CDATA #REQUIRED
		    missing_type CDATA #REQUIRED
		    coefficient_type CDATA #REQUIRED
		    length CDATA #REQUIRED
		    gace CDATA #REQUIRED
		    literal_type CDATA #REQUIRED
		    equivalence_class CDATA #REQUIRED>

-->


<!ELEMENT bool_cedent (literal*)>
<!ATTLIST bool_cedent id ID #REQUIRED
          name CDATA #REQUIRED
          db_name CDATA #REQUIRED
			    matrix_name CDATA #REQUIRED
			    task_name CDATA #REQUIRED
			    task_type CDATA #REQUIRED
			    cedent_type CDATA #REQUIRED
			    literal_cnt CDATA #REQUIRED
			    length CDATA #REQUIRED>
<!ELEMENT literal EMPTY>
<!ATTLIST literal underlying_attribute CDATA #REQUIRED
		    category_cnt CDATA #REQUIRED
		    missing_type CDATA #REQUIRED
		    coefficient_type CDATA #REQUIRED
		    length CDATA #REQUIRED
		    gace CDATA #REQUIRED
		    literal_type CDATA #REQUIRED
		    equivalence_class CDATA #REQUIRED>

<!-- Active elements - Attributes and Categories -->


  <!ELEMENT attribute (ctgr*, missing_value*)>
  <!ATTLIST attribute id ID #REQUIRED
                      db_name CDATA #REQUIRED
                      matrix_name CDATA #REQUIRED
                      attr_name CDATA #REQUIRED
                      creation CDATA #REQUIRED
                      ctgr_count CDATA #REQUIRED>  <!-- Kody To Chrzi: ??? name of source column -->
  <!ELEMENT ctgr EMPTY>
  <!ATTLIST ctgr name CDATA #REQUIRED
                 freq CDATA #REQUIRED> 
  <!ELEMENT missing_value EMPTY>
  <!ATTLIST missing_value name CDATA #REQUIRED>





  <!ELEMENT category (ctgr_def*)>
  <!ATTLIST category id ID #REQUIRED
                     db_name CDATA #REQUIRED
                     matrix_name CDATA #REQUIRED
                     attr_name CDATA #REQUIRED
                     ctgr_name CDATA #REQUIRED
                     ctgr_type CDATA #REQUIRED
                     ctgr_freq CDATA #REQUIRED
                     bool_type CDATA #REQUIRED
                     def_length CDATA #REQUIRED>
  <!ELEMENT ctgr_def EMPTY>
  <!ATTLIST ctgr_def definition CDATA #REQUIRED>


<!-- Active elements - Hypotheses -->

<!-- 4FT hypothesis-->
  
  <!ELEMENT hyp_4ft EMPTY>
  <!ATTLIST hyp_4ft id ID #REQUIRED
                    db_name CDATA #REQUIRED
                    matrix_name CDATA #REQUIRED
                    task_name CDATA #REQUIRED
                    a CDATA #REQUIRED
                    b CDATA #REQUIRED
                    c CDATA #REQUIRED
                    d CDATA #REQUIRED
  
                    conf CDATA #REQUIRED
                    d_conf CDATA #REQUIRED
                    e_conf CDATA #REQUIRED
                    support CDATA #REQUIRED
                    completeness CDATA #REQUIRED
                    avg_diff CDATA #REQUIRED
                    low_bnd_imp CDATA #REQUIRED
                    up_bnd_imp CDATA #REQUIRED
                    low_bnd_dbl_imp CDATA #REQUIRED
                    up_bnd_dbl_imp CDATA #REQUIRED
                    low_bnd_eq CDATA #REQUIRED
                    up_bnd_eq CDATA #REQUIRED
                    fisher CDATA #REQUIRED
                    chi_sq CDATA #REQUIRED
  
                    antecedent IDREF #IMPLIED
                    succedent IDREF #IMPLIED
                    condition IDREF #IMPLIED>   <!--antecedent,succedent,condition: references to ti_cedent -->

<!-- SD-4FT hypothesis-->

<!ELEMENT hyp_sd4ft EMPTY>
<!ATTLIST hyp_sd4ft id ID #REQUIRED
                    db_name CDATA #REQUIRED
                    matrix_name CDATA #REQUIRED
                    task_name CDATA #REQUIRED
                    a CDATA #REQUIRED
                    b CDATA #REQUIRED
                    c CDATA #REQUIRED
                    d CDATA #REQUIRED
                    e CDATA #REQUIRED
                    f CDATA #REQUIRED
                    g CDATA #REQUIRED
                    h CDATA #REQUIRED
  
                    conf1 CDATA #REQUIRED
                    d_conf1 CDATA #REQUIRED
                    e_conf1 CDATA #REQUIRED
                    support1 CDATA #REQUIRED
                    completeness1 CDATA #REQUIRED
                    avg_diff1 CDATA #REQUIRED
                    low_bnd_imp1 CDATA #REQUIRED
                    up_bnd_imp1 CDATA #REQUIRED
                    low_bnd_dbl_imp1 CDATA #REQUIRED
                    up_bnd_dbl_imp1 CDATA #REQUIRED
                    low_bnd_eq1 CDATA #REQUIRED
                    up_bnd_eq1 CDATA #REQUIRED
                    fisher1 CDATA #REQUIRED
                    chi_sq1 CDATA #REQUIRED
  
                    conf2 CDATA #REQUIRED
                    d_conf2 CDATA #REQUIRED
                    e_conf2 CDATA #REQUIRED
                    support2 CDATA #REQUIRED
                    completeness2 CDATA #REQUIRED
                    avg_diff2 CDATA #REQUIRED
                    low_bnd_imp2 CDATA #REQUIRED
                    up_bnd_imp2 CDATA #REQUIRED
                    low_bnd_dbl_imp2 CDATA #REQUIRED
                    up_bnd_dbl_imp2 CDATA #REQUIRED
                    low_bnd_eq2 CDATA #REQUIRED
                    up_bnd_eq2 CDATA #REQUIRED
                    fisher2 CDATA #REQUIRED
                    chi_sq2 CDATA #REQUIRED
                    
                    dr_sum CDATA #REQUIRED
                    df_conf CDATA #REQUIRED
                    df_dfui CDATA #REQUIRED
                    df_fue CDATA #REQUIRED
                    df_avg CDATA #REQUIRED
  
                    antecedent IDREF #IMPLIED
                    succedent IDREF #IMPLIED
                    condition IDREF #IMPLIED
                    set1 IDREF #IMPLIED
                    set2 IDREF #IMPLIED>
          <!--antecedent,succedent,condition, set1, set2: references to ti_cedent -->


<!-- KL hypothesis -->

  
  <!ELEMENT hyp_kl  (tab)>
  <!ATTLIST hyp_kl  id ID #REQUIRED
                    db_name CDATA #REQUIRED
                    matrix_name CDATA #REQUIRED
                    task_name CDATA #REQUIRED   
                    
                    sum CDATA #REQUIRED
                    min CDATA #REQUIRED
                    max CDATA #REQUIRED
                    chi_sq CDATA #REQUIRED
                    fnc_s CDATA #REQUIRED
                    fnc_r CDATA #REQUIRED
                    h_c CDATA #REQUIRED
                    h_r CDATA #REQUIRED
                    h_c_r CDATA #REQUIRED
                    mi CDATA #REQUIRED
                    aic CDATA #REQUIRED
                    kend CDATA #REQUIRED 
  
                    row_attributes IDREF #IMPLIED
                    column_attributes IDREF #IMPLIED
                    condition IDREF #IMPLIED>
                    <!--row_attribute(antecedent),column_attribute(succedent): references to ti_cat_cedent; condition: reference to ti_cedent -->

<!-- SD-KL hypothesis -->


<!ELEMENT hyp_sdkl  (tab,tab)>
<!ATTLIST hyp_sdkl  id ID #REQUIRED
                    db_name CDATA #REQUIRED
                    matrix_name CDATA #REQUIRED
                    task_name CDATA #REQUIRED   
                    
                    sum1 CDATA #REQUIRED
                    min1 CDATA #REQUIRED
                    max1 CDATA #REQUIRED
                    chi_sq1 CDATA #REQUIRED
                    fnc_s1 CDATA #REQUIRED
                    fnc_r1 CDATA #REQUIRED
                    h_c1 CDATA #REQUIRED
                    h_r1 CDATA #REQUIRED
                    h_c_r1 CDATA #REQUIRED
                    mi1 CDATA #REQUIRED
                    aic1 CDATA #REQUIRED
                    kend1 CDATA #REQUIRED 
  
                    sum2 CDATA #REQUIRED
                    min2 CDATA #REQUIRED
                    max2 CDATA #REQUIRED
                    chi_sq2 CDATA #REQUIRED
                    fnc_s2 CDATA #REQUIRED
                    fnc_r2 CDATA #REQUIRED
                    h_c2 CDATA #REQUIRED
                    h_r2 CDATA #REQUIRED
                    h_c_r2 CDATA #REQUIRED
                    mi2 CDATA #REQUIRED
                    aic2 CDATA #REQUIRED
                    kend2 CDATA #REQUIRED
  
                    da_sum CDATA #REQUIRED
                    da_min CDATA #REQUIRED
                    da_max CDATA #REQUIRED
                    dr_sum CDATA #REQUIRED
                    dr_min CDATA #REQUIRED
                    dr_max CDATA #REQUIRED
                       
                    row_attributes IDREF #IMPLIED
                    column_attributes IDREF #IMPLIED
                    condition IDREF #IMPLIED
                    set1 IDREF #IMPLIED
                    set2 IDREF #IMPLIED>
                  <!--row_attribute(antecedent),column_attribute(succedent): references to ti_cat_cedent
                      condition,set1,set2 : reference to ti_cedent-->

<!-- CF hypothesis -->

<!ELEMENT hyp_cf  (r)>
<!ATTLIST hyp_cf  id ID #REQUIRED
                    db_name CDATA #REQUIRED
                    matrix_name CDATA #REQUIRED
                    task_name CDATA #REQUIRED   
                    
                    sum CDATA #REQUIRED
                    min CDATA #REQUIRED
                    max CDATA #REQUIRED
                    v CDATA #REQUIRED
                    nom_var CDATA #REQUIRED
                    dor_var CDATA #REQUIRED
  
                    avg_a CDATA #REQUIRED
                    avg_g CDATA #REQUIRED
                    var CDATA #REQUIRED
                    st_dev CDATA #REQUIRED
                    skew CDATA #REQUIRED
                    asym CDATA #REQUIRED 
  
                    attributes IDREF #IMPLIED
                    condition IDREF #IMPLIED>
<!--attribute(cedent): reference to ti_cat_cedent; condition: reference to ti_cedent -->


<!-- SD-CF hypothesis -->

<!ELEMENT hyp_sdcf  (r,r)>
<!ATTLIST hyp_sdcf  id ID #REQUIRED
                    db_name CDATA #REQUIRED
                    matrix_name CDATA #REQUIRED
                    task_name CDATA #REQUIRED   
                    
                    sum1 CDATA #REQUIRED
                    min1 CDATA #REQUIRED
                    max1 CDATA #REQUIRED
                    v1 CDATA #REQUIRED
                    nom_var1 CDATA #REQUIRED
                    dor_var1 CDATA #REQUIRED
                    avg_a1 CDATA #REQUIRED
                    avg_g1 CDATA #REQUIRED
                    var1 CDATA #REQUIRED
                    st_dev1 CDATA #REQUIRED
                    skew1 CDATA #REQUIRED
                    asym1 CDATA #REQUIRED 
  
                    sum2 CDATA #REQUIRED
                    min2 CDATA #REQUIRED
                    max2 CDATA #REQUIRED
                    v2 CDATA #REQUIRED
                    nom_var2 CDATA #REQUIRED
                    dor_var2 CDATA #REQUIRED  
                    avg_a2 CDATA #REQUIRED
                    avg_g2 CDATA #REQUIRED
                    var2 CDATA #REQUIRED
                    st_dev2 CDATA #REQUIRED
                    skew2 CDATA #REQUIRED
                    asym2 CDATA #REQUIRED 
   
                    da_sum CDATA #REQUIRED
                    da_min CDATA #REQUIRED
                    da_max CDATA #REQUIRED
                    dr_sum CDATA #REQUIRED
                    dr_min CDATA #REQUIRED
                    dr_max CDATA #REQUIRED
    
                    attributes IDREF #IMPLIED
                    condition IDREF #IMPLIED
                    set1 IDREF #IMPLIED
                    set2 IDREF #IMPLIED>
<!--attribute(cedent): reference to ti_cat_cedent; condition,set1,set2: reference to ti_cedent -->


<!ELEMENT tab (r*)>
<!ELEMENT r (c*)>
<!ELEMENT c EMPTY >
<!ATTLIST c val CDATA #REQUIRED>
<!--tab: contingency table;  r: row;  c: column;  val: value-->



<!ELEMENT ti_cedent (ti_literal*)>
<!ATTLIST ti_cedent id ID #REQUIRED
                      type CDATA #REQUIRED>
<!--antecedent, succedent, condition -->
<!ELEMENT ti_literal EMPTY>
<!ATTLIST ti_literal id ID #REQUIRED
                       quant CDATA #REQUIRED   
                       value CDATA #REQUIRED>
<!--quant: name of the quantity used in hypothese, e. g. diastolic pressure  -->
<!--value: value of the quantity used in hypothese, e. g. <50;60) -->


                   
<!ELEMENT ti_attribute (ti_category*)>
<!ATTLIST ti_attribute id ID #REQUIRED
                      quant CDATA #REQUIRED   
                      type CDATA #REQUIRED>  <!--row attribute, column attribute, attribute -->
<!ELEMENT ti_category EMPTY>
<!ATTLIST ti_category value CDATA #REQUIRED>
<!--quant: name of the quantity used in hypothese, e. g. diastolic pressure  -->
<!--value: value of the quantity used in hypothese, e. g. <50;60), empty for rows and columns -->



<!-- Active elements Quantifiers -->

<!-- Toto je puvodni implementace, bylo predelano pouze na zakladni kvantifikatory

<!ELEMENT quantifier (basic_quantifier*)>
<!ATTLIST quantifier  id ID #REQUIRED
                    db_name CDATA #REQUIRED
                    matrix_name CDATA #REQUIRED
                    task_name CDATA #REQUIRED   
                    type CDATA #REQUIRED   
                    basic_count CDATA #REQUIRED>
-->
<!--basic_count: number of basic quantifiers -->
<!--type: type of quantifier (4FT, SD-4FT, KL, CF, .....) -->



<!ELEMENT quantifier (quant_item*)>
<!ATTLIST quantifier  id ID #REQUIRED
                    db_name CDATA #REQUIRED
                    matrix_name CDATA #REQUIRED
                    task_name CDATA #REQUIRED   
                    task_type CDATA #REQUIRED
                    name CDATA #REQUIRED
                    type CDATA #REQUIRED>
<!--name: basic quantifier name (type) (i.e. Founded implication, Chi-square, .....) -->
<!--type: type of basic quantifier (i.e. Aggregation, Functional ..) -->
<!--task_type: type of quantifier (4FT, SD-4FT, KL, CF, .....) -->

<!ELEMENT quant_item EMPTY>
<!ATTLIST quant_item name CDATA #REQUIRED
                    value CDATA #REQUIRED>
<!--quant_item: one item that can be set in basic quantifier (i.e. parameter and it's value)-->


<!-- Special Active elements for FE plugin -->

<!--ferda_box - AP "univerzalni krabicka"-->

<!ELEMENT ferda_box ((febox_property*, febox_socket*)*)>
<!ATTLIST ferda_box 	id ID #REQUIRED
      box_type CDATA #REQUIRED
			user_name CDATA #REQUIRED
			user_hint CDATA #IMPLIED>
<!-- -->

<!ELEMENT febox_property EMPTY>
<!ATTLIST febox_property name CDATA #REQUIRED
			  value CDATA #REQUIRED>
<!-- name: name of property
     value: value of property
-->
]>

 <active_list>  <hyp_cf id="hypCF1" db_name="c:\skola\sw projekt\dev\ReportAsistent\LMMetabase\LMEmpty2" matrix_name="Entry" task_name="pokus"  sum="0"  min="0"  max="0"  v="0"  nom_var="0"  dor_var="0"  avg_a="0"  avg_g="0"  var="0"  st_dev="0"  skew="0"  asym="0"  attributes="attr_hypCF1"  condition="cond_hypCF1"> <r>  <c val="12"/>  <c val="526"/>  <c val="723"/>  <c val="127"/>  <c val="21"/>  </r>  </hyp_cf>   <ti_attribute id="attr_hypCF1" quant="BMI" type="Attributes">  <ti_category value="podvaha"/>  <ti_category value="normal"/>  <ti_category value="nadvaha"/>  <ti_category value="obezita"/>  <ti_category value="tezka obezita"/>  </ti_attribute>  <ti_cedent id="cond_hypCF1" type="condition">  </ti_cedent>  <hyp_cf id="hypCF2" db_name="c:\skola\sw projekt\dev\ReportAsistent\LMMetabase\LMEmpty2" matrix_name="Entry" task_name="pokus"  sum="0"  min="0"  max="0"  v="0"  nom_var="0"  dor_var="0"  avg_a="0"  avg_g="0"  var="0"  st_dev="0"  skew="0"  asym="0"  attributes="attr_hypCF2"  condition="cond_hypCF2"> <r>  <c val="1210"/>  <c val="182"/>  <c val="9"/>  <c val="1"/>  <c val="15"/>  </r>  </hyp_cf>   <ti_attribute id="attr_hypCF2" quant="Dusnost" type="Attributes">  <ti_category value="nepritomna"/>  <ti_category value="stupen I"/>  <ti_category value="stupen II"/>  <ti_category value="stupen III"/>  <ti_category value="stupen IV"/>  </ti_attribute>  <ti_cedent id="cond_hypCF2" type="condition">  </ti_cedent>  <hyp_cf id="hypCF3" db_name="c:\skola\sw projekt\dev\ReportAsistent\LMMetabase\LMEmpty2" matrix_name="Entry" task_name="pokus"  sum="0"  min="0"  max="0"  v="0"  nom_var="0"  dor_var="0"  avg_a="0"  avg_g="0"  var="0"  st_dev="0"  skew="0"  asym="0"  attributes="attr_hypCF3"  condition="cond_hypCF3"> <r>  <c val="1032"/>  <c val="311"/>  <c val="52"/>  <c val="19"/>  <c val="3"/>  </r>  </hyp_cf>   <ti_attribute id="attr_hypCF3" quant="Bolhr" type="Attributes">  <ti_category value="neischemicka"/>  <ti_category value="pozitivni AP"/>  <ti_category value="ostatni"/>  <ti_category value="mozny IM"/>  <ti_category value="Join: nepritomna, neudano"/>  </ti_attribute>  <ti_cedent id="cond_hypCF3" type="condition">  </ti_cedent>  <hyp_cf id="hypCF4" db_name="c:\skola\sw projekt\dev\ReportAsistent\LMMetabase\LMEmpty2" matrix_name="Entry" task_name="pokus"  sum="0"  min="0"  max="0"  v="0"  nom_var="0"  dor_var="0"  avg_a="0"  avg_g="0"  var="0"  st_dev="0"  skew="0"  asym="0"  attributes="attr_hypCF4"  condition="cond_hypCF4"> <r>  <c val="0"/>  <c val="526"/>  <c val="0"/>  <c val="0"/>  <c val="0"/>  </r>  </hyp_cf>   <ti_attribute id="attr_hypCF4" quant="BMI" type="Attributes">  <ti_category value="podvaha"/>  <ti_category value="normal"/>  <ti_category value="nadvaha"/>  <ti_category value="obezita"/>  <ti_category value="tezka obezita"/>  </ti_attribute>  <ti_cedent id="cond_hypCF4" type="condition">  <ti_literal id ="tiCFLit79hypCF4" quant="BMI" value="normal"/>  </ti_cedent>  <hyp_cf id="hypCF5" db_name="c:\skola\sw projekt\dev\ReportAsistent\LMMetabase\LMEmpty2" matrix_name="Entry" task_name="pokus"  sum="0"  min="0"  max="0"  v="0"  nom_var="0"  dor_var="0"  avg_a="0"  avg_g="0"  var="0"  st_dev="0"  skew="0"  asym="0"  attributes="attr_hypCF5"  condition="cond_hypCF5"> <r>  <c val="473"/>  <c val="44"/>  <c val="2"/>  <c val="1"/>  <c val="6"/>  </r>  </hyp_cf>   <ti_attribute id="attr_hypCF5" quant="Dusnost" type="Attributes">  <ti_category value="nepritomna"/>  <ti_category value="stupen I"/>  <ti_category value="stupen II"/>  <ti_category value="stupen III"/>  <ti_category value="stupen IV"/>  </ti_attribute>  <ti_cedent id="cond_hypCF5" type="condition">  <ti_literal id ="tiCFLit80hypCF5" quant="BMI" value="normal"/>  </ti_cedent>  <hyp_cf id="hypCF6" db_name="c:\skola\sw projekt\dev\ReportAsistent\LMMetabase\LMEmpty2" matrix_name="Entry" task_name="pokus"  sum="0"  min="0"  max="0"  v="0"  nom_var="0"  dor_var="0"  avg_a="0"  avg_g="0"  var="0"  st_dev="0"  skew="0"  asym="0"  attributes="attr_hypCF6"  condition="cond_hypCF6"> <r>  <c val="386"/>  <c val="113"/>  <c val="15"/>  <c val="12"/>  <c val="0"/>  </r>  </hyp_cf>   <ti_attribute id="attr_hypCF6" quant="Bolhr" type="Attributes">  <ti_category value="neischemicka"/>  <ti_category value="pozitivni AP"/>  <ti_category value="ostatni"/>  <ti_category value="mozny IM"/>  <ti_category value="Join: nepritomna, neudano"/>  </ti_attribute>  <ti_cedent id="cond_hypCF6" type="condition">  <ti_literal id ="tiCFLit81hypCF6" quant="BMI" value="normal"/>  </ti_cedent>  <hyp_cf id="hypCF7" db_name="c:\skola\sw projekt\dev\ReportAsistent\LMMetabase\LMEmpty2" matrix_name="Entry" task_name="pokus"  sum="0"  min="0"  max="0"  v="0"  nom_var="0"  dor_var="0"  avg_a="0"  avg_g="0"  var="0"  st_dev="0"  skew="0"  asym="0"  attributes="attr_hypCF7"  condition="cond_hypCF7"> <r>  <c val="0"/>  <c val="0"/>  <c val="723"/>  <c val="0"/>  <c val="0"/>  </r>  </hyp_cf>   <ti_attribute id="attr_hypCF7" quant="BMI" type="Attributes">  <ti_category value="podvaha"/>  <ti_category value="normal"/>  <ti_category value="nadvaha"/>  <ti_category value="obezita"/>  <ti_category value="tezka obezita"/>  </ti_attribute>  <ti_cedent id="cond_hypCF7" type="condition">  <ti_literal id ="tiCFLit82hypCF7" quant="BMI" value="nadvaha"/>  </ti_cedent>  <hyp_cf id="hypCF8" db_name="c:\skola\sw projekt\dev\ReportAsistent\LMMetabase\LMEmpty2" matrix_name="Entry" task_name="pokus"  sum="0"  min="0"  max="0"  v="0"  nom_var="0"  dor_var="0"  avg_a="0"  avg_g="0"  var="0"  st_dev="0"  skew="0"  asym="0"  attributes="attr_hypCF8"  condition="cond_hypCF8"> <r>  <c val="605"/>  <c val="103"/>  <c val="6"/>  <c val="0"/>  <c val="9"/>  </r>  </hyp_cf>   <ti_attribute id="attr_hypCF8" quant="Dusnost" type="Attributes">  <ti_category value="nepritomna"/>  <ti_category value="stupen I"/>  <ti_category value="stupen II"/>  <ti_category value="stupen III"/>  <ti_category value="stupen IV"/>  </ti_attribute>  <ti_cedent id="cond_hypCF8" type="condition">  <ti_literal id ="tiCFLit83hypCF8" quant="BMI" value="nadvaha"/>  </ti_cedent>  <hyp_cf id="hypCF9" db_name="c:\skola\sw projekt\dev\ReportAsistent\LMMetabase\LMEmpty2" matrix_name="Entry" task_name="pokus"  sum="0"  min="0"  max="0"  v="0"  nom_var="0"  dor_var="0"  avg_a="0"  avg_g="0"  var="0"  st_dev="0"  skew="0"  asym="0"  attributes="attr_hypCF9"  condition="cond_hypCF9"> <r>  <c val="522"/>  <c val="167"/>  <c val="26"/>  <c val="7"/>  <c val="1"/>  </r>  </hyp_cf>   <ti_attribute id="attr_hypCF9" quant="Bolhr" type="Attributes">  <ti_category value="neischemicka"/>  <ti_category value="pozitivni AP"/>  <ti_category value="ostatni"/>  <ti_category value="mozny IM"/>  <ti_category value="Join: nepritomna, neudano"/>  </ti_attribute>  <ti_cedent id="cond_hypCF9" type="condition">  <ti_literal id ="tiCFLit84hypCF9" quant="BMI" value="nadvaha"/>  </ti_cedent>  <hyp_cf id="hypCF10" db_name="c:\skola\sw projekt\dev\ReportAsistent\LMMetabase\LMEmpty2" matrix_name="Entry" task_name="pokus"  sum="0"  min="0"  max="0"  v="0"  nom_var="0"  dor_var="0"  avg_a="0"  avg_g="0"  var="0"  st_dev="0"  skew="0"  asym="0"  attributes="attr_hypCF10"  condition="cond_hypCF10"> <r>  <c val="0"/>  <c val="0"/>  <c val="0"/>  <c val="127"/>  <c val="0"/>  </r>  </hyp_cf>   <ti_attribute id="attr_hypCF10" quant="BMI" type="Attributes">  <ti_category value="podvaha"/>  <ti_category value="normal"/>  <ti_category value="nadvaha"/>  <ti_category value="obezita"/>  <ti_category value="tezka obezita"/>  </ti_attribute>  <ti_cedent id="cond_hypCF10" type="condition">  <ti_literal id ="tiCFLit85hypCF10" quant="BMI" value="obezita"/>  </ti_cedent>  <hyp_cf id="hypCF11" db_name="c:\skola\sw projekt\dev\ReportAsistent\LMMetabase\LMEmpty2" matrix_name="Entry" task_name="pokus"  sum="0"  min="0"  max="0"  v="0"  nom_var="0"  dor_var="0"  avg_a="0"  avg_g="0"  var="0"  st_dev="0"  skew="0"  asym="0"  attributes="attr_hypCF11"  condition="cond_hypCF11"> <r>  <c val="101"/>  <c val="25"/>  <c val="1"/>  <c val="0"/>  <c val="0"/>  </r>  </hyp_cf>   <ti_attribute id="attr_hypCF11" quant="Dusnost" type="Attributes">  <ti_category value="nepritomna"/>  <ti_category value="stupen I"/>  <ti_category value="stupen II"/>  <ti_category value="stupen III"/>  <ti_category value="stupen IV"/>  </ti_attribute>  <ti_cedent id="cond_hypCF11" type="condition">  <ti_literal id ="tiCFLit86hypCF11" quant="BMI" value="obezita"/>  </ti_cedent>  <hyp_cf id="hypCF12" db_name="c:\skola\sw projekt\dev\ReportAsistent\LMMetabase\LMEmpty2" matrix_name="Entry" task_name="pokus"  sum="0"  min="0"  max="0"  v="0"  nom_var="0"  dor_var="0"  avg_a="0"  avg_g="0"  var="0"  st_dev="0"  skew="0"  asym="0"  attributes="attr_hypCF12"  condition="cond_hypCF12"> <r>  <c val="90"/>  <c val="25"/>  <c val="10"/>  <c val="0"/>  <c val="2"/>  </r>  </hyp_cf>   <ti_attribute id="attr_hypCF12" quant="Bolhr" type="Attributes">  <ti_category value="neischemicka"/>  <ti_category value="pozitivni AP"/>  <ti_category value="ostatni"/>  <ti_category value="mozny IM"/>  <ti_category value="Join: nepritomna, neudano"/>  </ti_attribute>  <ti_cedent id="cond_hypCF12" type="condition">  <ti_literal id ="tiCFLit87hypCF12" quant="BMI" value="obezita"/>  </ti_cedent>  </active_list>